"""
SwasthAI Guardian - Disease Prediction Model Training Script
Trains a Random Forest on rural India disease symptoms.
Run once: python train_disease_model.py
"""
import pandas as pd, joblib
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import Pipeline

TRAINING_DATA = [
    # TYPHOID - 20 samples
    ("high fever sustained days headache weakness stomach pain loss appetite", "Typhoid"),
    ("continuous fever body weakness abdomen pain no hunger nausea", "Typhoid"),
    ("fever one week headache diarrhea fatigue rose spots skin", "Typhoid"),
    ("bukhar sar dard kamzori pet dard bhook nahi", "Typhoid"),
    ("sustained high temperature chills constipation spleen enlarged", "Typhoid"),
    ("prolonged fever week abdominal tenderness lethargy coated tongue", "Typhoid"),
    ("fever stepwise increasing temperature mild cough stomach bloating", "Typhoid"),
    ("enteric fever high temperature headache slow pulse rose rash", "Typhoid"),
    ("high grade fever one week nausea vomiting abdominal discomfort weakness", "Typhoid"),
    ("continuous high fever constipation abdominal pain headache no appetite", "Typhoid"),
    ("salmonella fever prolonged weakness stomach pain loss appetite", "Typhoid"),
    ("week long fever fatigue stomach tenderness headache pale stool", "Typhoid"),
    ("fever nahi ja raha pet mein dard kamzori bhook nahi", "Typhoid"),
    ("seven day fever headache body ache stomach upset", "Typhoid"),
    ("persistent fever dull headache abdominal discomfort fatigue weakness", "Typhoid"),
    ("high fever abdominal bloating constipation body weakness no appetite", "Typhoid"),
    ("stepped fever week abdominal cramps fatigue headache", "Typhoid"),
    ("bukhar ek hafte se headache kamzori pet mein takleef", "Typhoid"),
    ("enteric fever sustained temperature constipation weakness abdominal pain", "Typhoid"),
    ("prolonged high temperature stomach discomfort no hunger weakness", "Typhoid"),

    # MALARIA - 20 samples
    ("high fever chills sweating headache muscle pain shivering", "Malaria"),
    ("fever shaking chills nausea vomiting fatigue body ache", "Malaria"),
    ("periodic fever every 2 days chills sweating headache", "Malaria"),
    ("bukhar kaanpna paseena sar dard ulti", "Malaria"),
    ("fever cycles rigors profuse sweating pallor splenomegaly", "Malaria"),
    ("bouts chills followed fever nausea muscle aches", "Malaria"),
    ("high fever cold stage chills hot stage sweating anemia", "Malaria"),
    ("intermittent fever shivers sweating episodes fatigue headache", "Malaria"),
    ("cyclical fever chills rigors sweating extreme weakness", "Malaria"),
    ("fever every alternate day chills sweating headache muscle pain", "Malaria"),
    ("bukhar thanda lagta hai paseena aata hai sar dard", "Malaria"),
    ("shivering followed fever sweating headache body ache weakness", "Malaria"),
    ("plasmodium fever chills rigors sweating pallor spleen", "Malaria"),
    ("fever cycles 48 hours shivering sweating fatigue", "Malaria"),
    ("recurrent fever chills nausea vomiting pallor jaundice", "Malaria"),
    ("high fever kaanpna sardarad ulti kamzori", "Malaria"),
    ("sudden fever chills sweating fatigue anemia enlarged spleen", "Malaria"),
    ("periodic fever rigors profuse sweating headache body ache", "Malaria"),
    ("intermittent high fever chills sweating muscle pain weakness", "Malaria"),
    ("bukhar thanda kaanpna paseena kamzori bhook nahi", "Malaria"),

    # DENGUE - 20 samples
    ("high fever severe headache pain behind eyes joint pain rash", "Dengue"),
    ("sudden high fever muscle pain skin rash nausea fatigue", "Dengue"),
    ("fever eye pain bone pain low platelet bleeding gums", "Dengue"),
    ("bukhar haddi dard aankhon mein dard skin rash kamzori", "Dengue"),
    ("high fever hemorrhagic rash platelet drop nosebleed vomiting", "Dengue"),
    ("severe joint pain fever skin rash extreme fatigue no appetite", "Dengue"),
    ("break bone fever headache retro orbital pain maculopapular rash", "Dengue"),
    ("fever muscle joint ache mild bleeding petechiae skin", "Dengue"),
    ("sudden high fever severe headache eye pain joint pain rash", "Dengue"),
    ("fever rash platelet low bleeding tendency body pain", "Dengue"),
    ("haddi dard aankhon ke peeche dard bukhar rash kamzori", "Dengue"),
    ("severe myalgia arthralgia fever rash thrombocytopenia", "Dengue"),
    ("high fever headache behind eyes pain rash on body weakness", "Dengue"),
    ("dengue rash fever platelet count low joint muscle pain", "Dengue"),
    ("sudden onset fever severe body pain rash nausea bleeding", "Dengue"),
    ("bukhar shareer mein dard aankhon mein dard rash kamzori", "Dengue"),
    ("fever 103 104 joint pain skin rash bleeding gums fatigue", "Dengue"),
    ("aedes fever rash thrombocytopenia headache eye pain", "Dengue"),
    ("high fever severe body ache rash petechiae nausea", "Dengue"),
    ("joint pain headache eye pain fever rash low platelets", "Dengue"),

    # TUBERCULOSIS - 20 samples
    ("persistent cough three weeks blood sputum weight loss night sweats", "Tuberculosis"),
    ("chronic cough fever weight loss fatigue chest pain night sweats", "Tuberculosis"),
    ("coughing blood prolonged cough breathing difficulty weakness sweating night", "Tuberculosis"),
    ("khansi khoon wajan kam bukhaar raat ko paseena", "Tuberculosis"),
    ("productive cough months hemoptysis low grade fever cachexia", "Tuberculosis"),
    ("cough more than 3 weeks loss weight anorexia fever lymph node", "Tuberculosis"),
    ("breathlessness chronic cough pleural effusion weight loss fatigue", "Tuberculosis"),
    ("pulmonary cough blood drenching night sweats fever evening wasting", "Tuberculosis"),
    ("cough more two months blood sputum weight loss fever sweating", "Tuberculosis"),
    ("prolonged cough hemoptysis night sweats weight loss weakness", "Tuberculosis"),
    ("khansi lambi kamzori wajan ghatna raat paseena", "Tuberculosis"),
    ("chronic productive cough blood tinged sputum fever weight loss", "Tuberculosis"),
    ("cough three months blood weight loss night fever sweating", "Tuberculosis"),
    ("persistent cough blood sputum weight loss low grade fever weakness", "Tuberculosis"),
    ("mahino se khansi khoon aana wajan kam raat ko bukhaar paseena", "Tuberculosis"),
    ("cough weeks blood fever chills night sweats cachexia", "Tuberculosis"),
    ("tb symptoms chronic cough hemoptysis weight loss night sweats", "Tuberculosis"),
    ("prolonged cough blood tinged sputum anorexia weight loss", "Tuberculosis"),
    ("khansi khoon aana raat ko paseena kamzori bhook nahi", "Tuberculosis"),
    ("chronic dry cough blood sputum weight loss evening fever", "Tuberculosis"),

    # CHOLERA - 18 samples
    ("severe watery diarrhea vomiting dehydration muscle cramps weakness", "Cholera"),
    ("rice water stools profuse diarrhea vomiting extreme thirst low bp", "Cholera"),
    ("sudden watery stool nausea vomiting dehydrated sunken eyes", "Cholera"),
    ("pani jaisi potty ulti pyas kamzori dehydration", "Cholera"),
    ("profuse diarrhea rice water rapid dehydration muscle cramps low urine", "Cholera"),
    ("acute watery diarrhea vomiting electrolyte loss shock extreme weakness", "Cholera"),
    ("severe loose watery stool vomiting dehydration cramps weakness", "Cholera"),
    ("profuse watery diarrhea no blood vomiting thirst weakness", "Cholera"),
    ("rice water diarrhea vomiting dehydration cramps weakness", "Cholera"),
    ("pani jaisi daast ulti pyas bahut zyada kamzori", "Cholera"),
    ("watery stool sudden dehydration vomiting sunken eyes cramping", "Cholera"),
    ("copious watery diarrhea vomiting leg cramps dehydration shock", "Cholera"),
    ("severe diarrhea no blood rice water stool vomiting dehydration", "Cholera"),
    ("vibrio cholera profuse diarrhea electrolyte imbalance dehydration", "Cholera"),
    ("sudden watery stool vomiting thirst weakness dehydrated", "Cholera"),
    ("bahut pani jaisi potty ulti dehydration kamzori", "Cholera"),
    ("acute diarrhea watery no fever vomiting cramps thirst", "Cholera"),
    ("profuse watery diarrhea rice water appearance vomiting dehydration", "Cholera"),

    # VIRAL FEVER - 20 samples
    ("mild fever runny nose sore throat cough body ache fatigue", "Viral Fever"),
    ("fever cold blocked nose throat pain headache tiredness", "Viral Fever"),
    ("low grade fever sneezing watery eyes weakness mild headache", "Viral Fever"),
    ("bukhar naak bana gale mein dard thakaan sar dard", "Viral Fever"),
    ("fever body pain chills runny nose loss appetite", "Viral Fever"),
    ("mild temperature cough sore throat fatigue joint ache", "Viral Fever"),
    ("fever 100 101 cold symptoms headache tiredness", "Viral Fever"),
    ("influenza fever myalgia rhinitis pharyngitis malaise", "Viral Fever"),
    ("low grade fever cold sneezing headache body ache weakness", "Viral Fever"),
    ("fever sore throat runny nose cough fatigue aches", "Viral Fever"),
    ("bukhar zukaam gale mein kharash thakaan sar dard", "Viral Fever"),
    ("mild fever cold nose blocked throat pain weakness", "Viral Fever"),
    ("seasonal fever cold cough headache body pain tiredness", "Viral Fever"),
    ("low fever sneezing runny nose headache fatigue", "Viral Fever"),
    ("bukhar naak beh rahi hai gala dukh raha hai", "Viral Fever"),
    ("mild temperature sore throat cough headache fatigue weakness", "Viral Fever"),
    ("fever cough cold body ache headache loss appetite", "Viral Fever"),
    ("thoda sa bukhar zukaam khansi thakaan sar dard", "Viral Fever"),
    ("mild fever runny nose throat pain fatigue body aches", "Viral Fever"),
    ("low grade fever cold symptoms cough headache weakness", "Viral Fever"),

    # PNEUMONIA - 20 samples
    ("high fever chest pain difficulty breathing cough phlegm chills", "Pneumonia"),
    ("breathlessness chest tightness fever productive cough fatigue", "Pneumonia"),
    ("severe cough breathing difficulty high temperature chest pain sweating", "Pneumonia"),
    ("saans lene mein takleef seene mein dard bukhaar khansi", "Pneumonia"),
    ("lobar pneumonia fever pleuritic chest pain cough sputum tachycardia", "Pneumonia"),
    ("consolidation lung high fever rusty sputum dyspnea rigors", "Pneumonia"),
    ("chest infection fever breathlessness crackles reduced breath sounds", "Pneumonia"),
    ("fever high cough green yellow sputum ribs hurt breathing", "Pneumonia"),
    ("high fever chest pain shortness breath productive cough shivering", "Pneumonia"),
    ("breathlessness chest tightness high fever cough with mucus weakness", "Pneumonia"),
    ("seene mein dard saans ki takleef bukhaar balgam khansi", "Pneumonia"),
    ("severe chest infection high fever difficulty breathing cough", "Pneumonia"),
    ("lung infection fever chest pain breathlessness mucus cough", "Pneumonia"),
    ("high temperature chest pain breathing problem cough phlegm", "Pneumonia"),
    ("saans nahi aa rahi seene mein dard bukhaar khansi balgam", "Pneumonia"),
    ("fever chills chest pain productive cough dyspnea fatigue", "Pneumonia"),
    ("chest pain breathing difficulty high fever cough mucus sweating", "Pneumonia"),
    ("pneumonia fever chest tightness breathlessness sputum cough", "Pneumonia"),
    ("lung infection breathing hard chest pain fever cough", "Pneumonia"),
    ("seene mein dard saans fulna bukhaar balgam wali khansi", "Pneumonia"),

    # ANAEMIA - 18 samples
    ("weakness fatigue pale skin dizziness shortness breath exertion", "Anaemia"),
    ("extreme tiredness paleness breathlessness cold hands feet headache", "Anaemia"),
    ("low energy pale conjunctiva weakness fainting rapid heartbeat", "Anaemia"),
    ("kamzori chakkar thakaan pale rang saans fulna", "Anaemia"),
    ("haemoglobin low fatigue pallor dyspnea exertion palpitations", "Anaemia"),
    ("iron deficiency tiredness brittle nails pale face weakness", "Anaemia"),
    ("weakness dizziness paleness tiredness breathlessness on effort", "Anaemia"),
    ("fatigue pale conjunctiva weakness breathlessness fast heartbeat", "Anaemia"),
    ("kamzori thakaan chakkar aana pale skin", "Anaemia"),
    ("extreme weakness pale face tiredness breathlessness cold extremities", "Anaemia"),
    ("low hemoglobin weakness fatigue pallor breathlessness palpitation", "Anaemia"),
    ("bahut kamzori thakaan chakkar khoon ki kami", "Anaemia"),
    ("fatigue pallor breathlessness on exertion cold hands weakness", "Anaemia"),
    ("weakness tiredness dizziness pale skin fast heart rate", "Anaemia"),
    ("khoon ki kami kamzori thakaan saans fulna chakkar", "Anaemia"),
    ("anaemia weakness pale conjunctiva fatigue dyspnea palpitations", "Anaemia"),
    ("iron deficient weakness tiredness pale face cold hands breathless", "Anaemia"),
    ("thakaan kamzori chakkar aana saans ki kami", "Anaemia"),

    # JAUNDICE - 18 samples
    ("yellow skin yellow eyes dark urine fatigue nausea abdominal pain", "Jaundice"),
    ("yellowing eyes skin itching pale stools vomiting weakness", "Jaundice"),
    ("jaundice dark brown urine clay colored stool nausea liver pain", "Jaundice"),
    ("aankhein peeli chamdi peeli peshab peela kamzori bukhar", "Jaundice"),
    ("icteric hepatomegaly anorexia bilirubin high pruritus", "Jaundice"),
    ("hepatitis yellow discoloration right upper quadrant pain malaise", "Jaundice"),
    ("yellow eyes skin dark urine fatigue stomach pain nausea", "Jaundice"),
    ("yellowing of eyes body weakness dark urine nausea vomiting", "Jaundice"),
    ("aankhein aur chamdi peeli ho gayi peshab gehra", "Jaundice"),
    ("liver problem yellow eyes dark urine fatigue abdominal pain", "Jaundice"),
    ("icteric yellow eyes skin pale stool dark urine fatigue", "Jaundice"),
    ("peeli aankhein peela peshab pet mein dard thakaan", "Jaundice"),
    ("hepatitis yellow skin eyes dark urine nausea weakness fever", "Jaundice"),
    ("bilirubin elevated jaundice itching dark urine fatigue", "Jaundice"),
    ("aankhein peeli twacha peeli peshab peela nausea weakness", "Jaundice"),
    ("yellow sclera yellow skin clay stool dark urine nausea", "Jaundice"),
    ("jaundice itching fatigue yellow eyes dark urine pale stool", "Jaundice"),
    ("aankhein peeli peshab gehra rang pet dard kamzori", "Jaundice"),

    # DYSENTERY - 18 samples
    ("diarrhea blood mucus stomach cramps fever vomiting", "Dysentery"),
    ("bloody stool painful diarrhea abdominal cramps nausea fever", "Dysentery"),
    ("loose stool blood tenesmus abdominal pain weakness", "Dysentery"),
    ("blood pichad potty pet mein dard bukhar ulti", "Dysentery"),
    ("amoebic dysentery intermittent diarrhea blood mucus colicky pain", "Dysentery"),
    ("bacillary dysentery fever cramps frequent bloody stools dehydration", "Dysentery"),
    ("bloody diarrhea cramps fever nausea weakness dehydration", "Dysentery"),
    ("diarrhea with blood stomach pain fever nausea weakness", "Dysentery"),
    ("blood mucus stool abdominal pain fever dehydration", "Dysentery"),
    ("khoon aur balgam potty pet mein dard bukhar ulti", "Dysentery"),
    ("frequent bloody stool cramping fever weakness dehydration", "Dysentery"),
    ("blood stool diarrhea stomach cramps fever vomiting weakness", "Dysentery"),
    ("khoon wali potty pet mein dard thakaan bukhar", "Dysentery"),
    ("dysentery bloody loose motion stomach cramps fever", "Dysentery"),
    ("blood in stool abdominal cramping fever nausea weakness", "Dysentery"),
    ("tenesmus bloody diarrhea cramps fever weakness dehydration", "Dysentery"),
    ("khoon ki potty pet dard bukhar kamzori ulti", "Dysentery"),
    ("mucus blood stool stomach pain fever vomiting fatigue", "Dysentery"),

    # CHICKENPOX - 18 samples
    ("itchy blisters all over body fever red spots vesicles", "Chickenpox"),
    ("blisters rash fever itching vesicles face body arms", "Chickenpox"),
    ("pox marks fluid filled blisters fever itching loss appetite", "Chickenpox"),
    ("chechak khujali chchale bukhar daane poore badan pe", "Chickenpox"),
    ("varicella pruritic vesicular rash low grade fever malaise", "Chickenpox"),
    ("itchy rash blisters fever all over body", "Chickenpox"),
    ("fluid blisters body fever itching loss appetite", "Chickenpox"),
    ("pox vesicles fever itching spreading rash", "Chickenpox"),
    ("daane khujali chchale bukhar poore badan mein", "Chickenpox"),
    ("chickenpox blisters fever itching rash all over", "Chickenpox"),
    ("itchy spots becoming blisters mild fever weakness", "Chickenpox"),
    ("vesicular rash fever itching spreading face body", "Chickenpox"),
    ("chechak chchale khujali thoda bukhar", "Chickenpox"),
    ("pox rash blisters fever itching body arms face", "Chickenpox"),
    ("fluid filled spots fever itching spreading rash", "Chickenpox"),
    ("daane nikle hain poore badan mein khujali bukhar", "Chickenpox"),
    ("itchy blisters fever weakness loss of appetite", "Chickenpox"),
    ("vesicles body face arms fever itching rash", "Chickenpox"),

    # MEASLES - 18 samples
    ("high fever cough runny nose red eyes skin rash starting face", "Measles"),
    ("rash spreading face body fever cough red watery eyes", "Measles"),
    ("koplik spots maculopapular rash fever coryza conjunctivitis", "Measles"),
    ("khasra daane bukhaar aankhein laal khansi naak bana", "Measles"),
    ("rubeola high fever prodrome cough rash spreading downward photophobia", "Measles"),
    ("rash starting face spreading body fever cough red eyes", "Measles"),
    ("fever rash spreading red eyes runny nose cough weakness", "Measles"),
    ("measles rash face body fever cough watery eyes", "Measles"),
    ("khasra bukhar daane aankhein laal khansi", "Measles"),
    ("maculopapular rash fever red eyes cough runny nose", "Measles"),
    ("rash on face spreading down body high fever cough", "Measles"),
    ("fever red eyes cough rash starting on face", "Measles"),
    ("daane munh se shuru poore badan mein bukhar aankhein laal", "Measles"),
    ("measles koplik spots rash fever cough photophobia", "Measles"),
    ("red eyes runny nose cough rash body fever weakness", "Measles"),
    ("khasra daane munh se shuru bukhar aankhen laal naak bana", "Measles"),
    ("high fever rash starting face spreading body watery eyes cough", "Measles"),
    ("morbilli rash fever cough coryza conjunctivitis koplik spots", "Measles"),
    # HEATSTROKE - 15 samples
    ("very high body temperature confusion dizziness no sweating hot dry skin collapse", "Heatstroke"),
    ("body temperature 40 celsius confusion disorientation fainting hot skin", "Heatstroke"),
    ("garmi mein behosh hona tez bukhaar paseena nahi aana confusion", "Heatstroke"),
    ("extreme heat exposure fever above 104 confusion loss consciousness dry skin", "Heatstroke"),
    ("sun stroke no sweating very high temperature fainting", "Heatstroke"),
    ("heat exhaustion confusion dizziness nausea high body temperature dry skin", "Heatstroke"),
    ("body overheating red hot dry skin confusion rapid pulse collapse", "Heatstroke"),
    ("garmi se behoshi tez bukhaar paseena nahi sar mein dard", "Heatstroke"),
    ("hyperthermia confusion rapid heartbeat very hot skin no perspiration weakness", "Heatstroke"),
    ("heat stroke 40 celsius body confusion disorientation dry skin rapid heart", "Heatstroke"),
    ("sun exposure high fever no sweat confusion fainting headache", "Heatstroke"),
    ("garmi mein sir ghoomna bukhaar hot skin behosh", "Heatstroke"),
    ("body temperature extremely high confusion dry hot skin collapsed", "Heatstroke"),
    ("severe heat exposure above 40 celsius no sweating confusion collapse", "Heatstroke"),
    ("dhoop mein rehna hot dry skin tez bukhaar behosh", "Heatstroke"),

    # SNAKEBITE - 15 samples
    ("snake bite swelling pain fang marks dizziness nausea vomiting", "Snakebite"),
    ("saanp ne kata soojan dard behoshi ulti chakkar", "Snakebite"),
    ("bite marks swelling limb pain numbness vomiting blurred vision", "Snakebite"),
    ("snakebite fang marks swelling spreading pain paralysis breathing difficulty", "Snakebite"),
    ("snake bite paralysis numbness swelling drooling convulsions", "Snakebite"),
    ("saanp ke daanth ka nishaan soojan dard numbness", "Snakebite"),
    ("puncture wounds swelling limb pain nausea vomiting breathing problem", "Snakebite"),
    ("snake envenomation swelling necrosis pain vomiting blurred vision weakness", "Snakebite"),
    ("bite leg arm soojan zyada dard ulti behoshi", "Snakebite"),
    ("snake bite two fang marks swelling spreading rapid heartbeat dizziness", "Snakebite"),
    ("venomous bite swelling numbing pain moving up limb drooling convulsion", "Snakebite"),
    ("saanp ne daanth maara soojan numb ho gaya dard ulti", "Snakebite"),
    ("fang marks pain spreading swelling bleeding wound dizziness", "Snakebite"),
    ("snake bite pain numbness paralysis vomiting breathing difficulty", "Snakebite"),
    ("saanp kata hai soojan dard behoshi saans lene mein takleef", "Snakebite"),

    # ACUTE RESPIRATORY INFECTION - 15 samples
    ("fever cough breathing difficulty sore throat body ache fatigue loss smell", "Acute Respiratory Infection"),
    ("high fever dry cough breathlessness fatigue loss taste smell", "Acute Respiratory Infection"),
    ("cough fever body pain headache weakness breathing problem", "Acute Respiratory Infection"),
    ("bukhar khansi saans ki takleef thakaan nasam mein dard", "Acute Respiratory Infection"),
    ("sore throat fever runny nose cough fatigue body pain breathing difficulty", "Acute Respiratory Infection"),
    ("high fever cough shortness breath weakness loss appetite", "Acute Respiratory Infection"),
    ("fever persistent dry cough fatigue difficulty breathing", "Acute Respiratory Infection"),
    ("bukhar khansi thakaan saans nahi aa rahi khana nahi khana", "Acute Respiratory Infection"),
    ("respiratory infection cough fever breathing problem extreme fatigue", "Acute Respiratory Infection"),
    ("cough with fever difficulty breathing weakness body ache headache", "Acute Respiratory Infection"),
    ("viral respiratory fever cough breathlessness loss of smell and taste", "Acute Respiratory Infection"),
    ("tez bukhar sukhi khansi thakaan saans ki takleef", "Acute Respiratory Infection"),
    ("fever cough shortness breath loss smell body weakness", "Acute Respiratory Infection"),
    ("high fever cough sore throat fatigue diarrhea body ache", "Acute Respiratory Infection"),
    ("bukhar khansi jism mein dard saans ki takleef kamzori", "Acute Respiratory Infection"),
    ("kaichal thalaivaali vayiru vali pasiyilla kamayosam", "Typhoid"),
    ("neetitta kaichal vayiru vali thalarchi", "Typhoid"),
    ("oru vaaram kaichal thalaivaali vayiru thalarchi", "Typhoid"),
    ("jvaaram naale irukku thalaivaali pasi illai kamayosam", "Typhoid"),
    ("nirantara kaichal vayiru kuzhambu thalaivaali kamayosam", "Typhoid"),
    ("kaichal nirungal viyarvai thalaivaali thalarchi malaria", "Malaria"),
    ("kaichal oer irandhu naal vidum nirungal viyarvai malaria", "Malaria"),
    ("nirungal pinnadi kaichal viyarvai thalaivaali malaria", "Malaria"),
    ("maari kaichal nirungal viyarvai kamayosam malaria", "Malaria"),
    ("idaiveli kaichal nirungal viyarvai thalarchi malaria", "Malaria"),
    ("dengue kaichal kal vaali thalaivaali kan pinna vaali", "Dengue"),
    ("dengue kaichal jaathi kuraival kamayosam thalarchi", "Dengue"),
    ("koorai kaichal teri jaathi kurai thalarchi kal vaali", "Dengue"),
    ("kaichal teri kan vaali kal kal vaali kamayosam dengue", "Dengue"),
    ("kaichal talai pinna kal vaali teri kan vaali dengue", "Dengue"),
    ("iraimookku irumal iraththam thookam izhapu uzhaippu", "Tuberculosis"),
    ("neetitta irumal iraththam vanthu thalarchi uzhaippu", "Tuberculosis"),
    ("irandu maatha irumal iraththam kaichal thookam viyarvai", "Tuberculosis"),
    ("iru maasa irumal uzhaippu kaichal iravil viyarvai", "Tuberculosis"),
    ("neettam irumal iru maasam kaichal thookam izhapu", "Tuberculosis"),
    ("veytham therindhu vanthu vomi valandhu kaichal thakam", "Cholera"),
    ("arisi thanni pola moonru valandhu kamayosam thakam", "Cholera"),
    ("kaichal illama veytham thanni pola vanthu thalarchi", "Cholera"),
    ("thanni peyar vomi thaakam thalarchi kamayosam cholera", "Cholera"),
    ("rice water stool vomi thakam thalarchi cholera", "Cholera"),
    ("sirukaichal thalaivaali kal vaali thalarchi sali irumal", "Viral Fever"),
    ("kaichal jalanam ookkam irumal thalaivaali sali", "Viral Fever"),
    ("sirukaichal kannai ookkam mukku ozukkam thalarchi", "Viral Fever"),
    ("thalarchi thalaivaali kaichal sali irumal kal vaali", "Viral Fever"),
    ("mild kaichal mukkul ozukkam sali thalarchi ookkam", "Viral Fever"),
    ("kaichal maarbu vaali moochu thittam irumal balgam", "Pneumonia"),
    ("maarbil veytham kaichal moochu thittam balgam irumal", "Pneumonia"),
    ("moochu thittam maarbu vaali kaichal balgam irumal", "Pneumonia"),
    ("thalarchi maarbu vaali kaichal balgam irumal svaasam", "Pneumonia"),
    ("svaasam thittam maarbu vaali kaichal irumal balgam", "Pneumonia"),
    ("thalarchi palor chakravakam ookkamilla moochu thittam ratham", "Anaemia"),
    ("rattha kammi thalarchi ookkamilla palor moochu thittam", "Anaemia"),
    ("thalarchi rattha kammi sali palor chakravakam", "Anaemia"),
    ("ookkamilla thalarchi pazhuthu moochu thittam ratham", "Anaemia"),
    ("irattha kuraivu thalarchi chakravakam moochu thittam", "Anaemia"),
    ("kan peela kamayosam vayiru vaali kaichal siru neer peela", "Jaundice"),
    ("thol peela siru neer peela thalarchi kaichal vayiru", "Jaundice"),
    ("kan peela iruppam kamayosam vayiru vaali thalarchi", "Jaundice"),
    ("thol peela thalarchi siru neer peela kaichal vomii", "Jaundice"),
    ("jaundice kan peela thol peela siru neer peela kamayosam", "Jaundice"),
    ("iraththa moonru vayiru vaali kaichal vomi thalarchi", "Dysentery"),
    ("iraththa peyar vayiru vaali kaichal thalarchi", "Dysentery"),
    ("balgam moonru vayiru vaali kaichal thalarchi vomii", "Dysentery"),
    ("iraththa peyar thalarchi kaichal vayiru kuzhambu", "Dysentery"),
    ("bloody moonru vayiru kaichal kamayosam vomii", "Dysentery"),
    ("sarumpu muzhuthu kaichal teri tholarchi", "Chickenpox"),
    ("sarumpu kaichal teri muzhuthu balam tholarchi", "Chickenpox"),
    ("teri kaichal sarumpu muzhuthu kamayosam", "Chickenpox"),
    ("kaichal sarumpu neerppai muzhuthu tholarchi", "Chickenpox"),
    ("chickenpox sarumpu kaichal teri muzhuthu balam", "Chickenpox"),
    ("kaichal irumal kan sivappu teri vanthu measles", "Measles"),
    ("teri mukkal thodangi muzhuthu patsai thalarchi irumal", "Measles"),
    ("kaichal irumal teri mukkal sivappu kan", "Measles"),
    ("koplik tholi teri kaichal irumal sivappu measles", "Measles"),
    ("high fever teri mukkal kaichal kan sivappu sali", "Measles"),
    ("maikkumidam kaichal viyarvai illai thalarchi heatstroke", "Heatstroke"),
    ("veyilil irukka maayakam uchcha kaichal viyarvai illai", "Heatstroke"),
    ("veyil kaichal viyarvai illai maayakam thalarchi", "Heatstroke"),
    ("uchcha veppam kaichal kuzhappam thalarchi maayakam", "Heatstroke"),
    ("heatstroke viyarvai illai uchcha veppam maayakam", "Heatstroke"),
    ("pambu kadichathu veekam vaali maayakam vomi snakebite", "Snakebite"),
    ("pambu theidum veekam kal vaali moochu thittam", "Snakebite"),
    ("pambu kadichathu veekam vaali moochu thittam maayakam", "Snakebite"),
    ("pambu kadichathu vomi chakravakam veekam vaali", "Snakebite"),
    ("snakebite veekam vaali moochu thittam maayakam vomi", "Snakebite"),
    ("kaichal irumal moochu thittam thalarchi svaasam ari", "Acute Respiratory Infection"),
    ("thodam kaichal irumal moochu thittam thalarchi", "Acute Respiratory Infection"),
    ("kaichal irumal moochu thittam thalarchi kamayosam ari", "Acute Respiratory Infection"),
    ("viral kaichal irumal moochu thittam uchcha thalarchi", "Acute Respiratory Infection"),
    ("respiratory kaichal irumal svaasam thittam thalarchi", "Acute Respiratory Infection"),
    ("fever", "Viral Fever"),
    ("fever cough", "Viral Fever"),
    ("fever cough weakness", "Viral Fever"),
    ("fever cough headache", "Viral Fever"),
    ("fever headache weakness", "Typhoid"),
    ("fever headache vomiting", "Malaria"),
    ("fever cough chest_pain breathing", "Pneumonia"),
    ("fever cough breathing weakness", "Pneumonia"),
    ("fever chest_pain breathing", "Pneumonia"),
    ("chest_pain breathing", "Pneumonia"),
    ("fever dizziness weakness", "Anaemia"),
    ("weakness dizziness", "Anaemia"),
    ("fever cough bleeding", "Tuberculosis"),
    ("cough bleeding weakness", "Tuberculosis"),
    ("fever vomiting diarrhea weakness", "Cholera"),
    ("vomiting diarrhea weakness", "Cholera"),
    ("fever vomiting bleeding diarrhea", "Dysentery"),
    ("fever rash itching", "Chickenpox"),
    ("fever rash cough", "Measles"),
    ("fever no sweating confusion dizziness", "Heatstroke"),
    ("swelling pain bite vomiting", "Snakebite"),
    ("fever cough breathing", "Acute Respiratory Infection"),
    ("cough for months blood coming out night sweat weight loss", "Tuberculosis"),
    ("prolonged cough with blood loss of appetite evening fever night sweats", "Tuberculosis"),
    ("mahino se khansi khoon ata hai raat ko paseena aur wajan kam", "Tuberculosis"),
    ("hemoptysis night sweats cachexia prolonged cough weakness", "Tuberculosis"),
    ("khansi mein khoon raat ko paseena wajan ghatna bukhaar thakaan", "Tuberculosis"),
    ("chronic cough blood tinged weight loss sweating at night fever", "Tuberculosis"),
    ("productive cough blood fever only evenings weight loss sweating", "Tuberculosis"),
    ("long standing cough blood fever night sweats losing weight fatigue", "Tuberculosis"),
    ("rash starting on face spreading down to body with high fever cough", "Measles"),
    ("face rash spreading whole body fever cough watery red eyes measles", "Measles"),
    ("koplik spots white inside mouth fever rash spreads down measles", "Measles"),
    ("high fever rash begins face then neck then trunk cough red eyes", "Measles"),
    ("mukh ke andar daag phir pura badan mein daane bukhar aankhein laal", "Measles"),
    ("fever rash from hairline downward red eyes runny nose cough measles", "Measles"),
    ("maculopapular rash starting face ears high fever red eyes cough", "Measles"),
    ("daane pehle munh pe phir neeche bukhar aankhein laal naak bana", "Measles"),
    ("fever cough breathing difficulty throat pain body ache no smell taste", "Acute Respiratory Infection"),
    ("dry persistent cough high fever breathlessness difficulty breathing", "Acute Respiratory Infection"),
    ("saans ki takleef khansi bukhar seene mein tightness thakaan gandh nahi", "Acute Respiratory Infection"),
    ("severe cough fever difficulty breathing short of breath oxygen low", "Acute Respiratory Infection"),
    ("fever cough loss of smell and taste extreme fatigue respiratory", "Acute Respiratory Infection"),
    ("khansi saans ki takleef bukhar thakaan gandh na aana khana swad nahi", "Acute Respiratory Infection"),
    ("respiratory illness fever dry cough breathlessness weakness no taste", "Acute Respiratory Infection"),
    ("upper respiratory infection fever cough sore throat bodyache breathing", "Acute Respiratory Infection"),
    ("fever for exactly one week getting higher each day then constipation", "Typhoid"),
    ("step-ladder fever week constipation then diarrhea headache typhoid", "Typhoid"),
    ("ek hafte se bukhar roz thoda zyada hota hai pet mein dard bhook nahi", "Typhoid"),
    ("enteric fever one week abdomen tender slow heartbeat rose spots", "Typhoid"),
    ("continuous high fever one week stomach pain constipation headache weak", "Typhoid"),
    ("ek hafte bukhar badh raha hai pet phula hua bhook nahi hai kamzori", "Typhoid"),
    ("sustained week long fever slow pulse hepatosplenomegaly abdominal pain", "Typhoid"),
    ("fever day after day higher no appetite constipation bloated abdomen", "Typhoid"),
]

df = pd.DataFrame(TRAINING_DATA, columns=["symptoms", "disease"])
print(f"[OK] Dataset: {len(df)} samples, {df['disease'].nunique()} classes")
print(f"   Per class: min={df['disease'].value_counts().min()}, max={df['disease'].value_counts().max()}\n")

X, y = df["symptoms"], df["disease"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Two complementary estimators:
# RF  — captures term co-occurrences, generalises across symptom phrasing
# GB  — boosts on hard/misclassified edge cases, improves precision on rare diseases
rf  = RandomForestClassifier(n_estimators=250, max_depth=50, min_samples_split=3,
                              class_weight="balanced", random_state=42, n_jobs=-1)
gb  = GradientBoostingClassifier(n_estimators=150, learning_rate=0.08,
                                  max_depth=6, random_state=42)
voting = VotingClassifier(estimators=[("rf", rf), ("gb", gb)], voting="soft", weights=[2, 1])

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_features=5000, sublinear_tf=True)),
    ("clf", voting)
])

print("[...] Training RF+GradientBoosting Ensemble (soft-voting)...")
pipeline.fit(X_train, y_train)

# Cross-validation for honest accuracy
cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring="accuracy")
print(f"[OK] 5-Fold Cross-Val Accuracy: {cv_scores.mean()*100:.1f}% (+/- {cv_scores.std()*100:.1f}%)")

y_pred = pipeline.predict(X_test)
test_acc = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, zero_division=0)
print(f"[RESULT] Test Accuracy: {test_acc * 100:.1f}%")
print(report)

joblib.dump(pipeline, "disease_model.pkl")
print("[SAVED] disease_model.pkl")

with open("model_accuracy.txt", "w") as f:
    f.write("SwasthAI Guardian - Disease Prediction Model\n")
    f.write("=" * 50 + "\n")
    f.write(f"Algorithm     : Random Forest Classifier\n")
    f.write(f"Vectorizer    : TF-IDF (unigrams + bigrams)\n")
    f.write(f"Training set  : {len(X_train)} samples\n")
    f.write(f"Test set      : {len(X_test)} samples\n")
    f.write(f"CV Accuracy   : {cv_scores.mean()*100:.1f}% (+/- {cv_scores.std()*100:.1f}%)\n")
    f.write(f"Test Accuracy : {test_acc * 100:.1f}%\n")
    f.write(f"Disease Classes ({df['disease'].nunique()}): {sorted(df['disease'].unique())}\n\n")
    f.write(f"Classification Report:\n{report}\n")

print("[DONE] Model ready. Restart main.py (uvicorn) to use it.")
