import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  "hi": {
    "dashboard": "नागरिक डैशबोर्ड",
    "welcome_back": "आपका स्वागत है। आज हम आपकी कैसे मदद कर सकते हैं?",
    "network_connected": "नेटवर्क कनेक्टेड",
    "swasthai": "स्वस्थAI",
    "national_impact": "राष्ट्रीय स्वास्थ्य प्रभाव",
    "tagline": "हम गांव के लोगों को सीधे डॉक्टरों और बेहतर इलाज से जोड़ते हैं।",
    "portal_access": "खोलें",
    "join_network": "जुड़ें",
    "citizens_covered": "नागरिक कवर किए गए",
    "network_uptime": "नेटवर्क अपटाइम",
    "villages_reached": "गांवों तक पहुंचे",
    "everything_you_need": "अच्छे स्वास्थ्य के लिए",
    "for_good_health": "सब कुछ",
    "get_started_now": "अभी शुरू करें",
    "ready_to_transform": "क्या आप ग्रामीण स्वास्थ्य को बदलने के लिए तैयार हैं?",
    "join_thousands": "हजारों आशा कार्यकर्ताओं, डॉक्टरों और नागरिकों से जुड़ें जो व्यापक स्वास्थ्य बुनियादी ढांचे के भविष्य का निर्माण कर रहे हैं।",
    "footer_text": "© 2026 स्वस्थAI हेल्थकेयर प्लेटफॉर्म। सर्वाधिकार सुरक्षित। IEEE प्रमाणित।",
    "services": {
      "maternal": "मातृ कल्याण",
      "maternal_desc": "गोपनीय क्लिनिकल मार्गदर्शन, मासिक धर्म ट्रैकिंग और मातृ सहायता प्राप्त करें।",
      "access_portal": "पोर्टल खोलें",
      "symptoms": "स्मार्ट निदान",
      "symptoms_desc": "स्मार्ट टूल से अपनी बीमारी की जांच करें।",
      "how_feeling": "बताएं आप कैसा महसूस कर रहे हैं?",
      "check_symptoms": "लक्षण जांचें",
      "analyzing": "विश्लेषण हो रहा है...",
      "emergency": "आपातकालीन केंद्र",
      "immediate_assist": "त्वरित सहायता",
      "ambulance_desc": "क्या आपको तत्काल एम्बुलेंस या आशा कार्यकर्ता की आवश्यकता है? जीपीएस स्थान साझा किया जाएगा।",
      "request_ambulance": "एम्बुलेंस बुलाएं",
      "dispatching": "भेजा जा रहा है...",
      "teleclinic": "टेली-मेडिसिन",
      "tele_desc": "शहर के डॉक्टरों से सीधे वीडियो कॉल परामर्श।",
      "academy": "स्वास्थ्य जागरूकता",
      "academy_desc": "स्वस्थ रहने, पोषण और टीकाकरण की जानकारी।",
      "voice": "आवाज सहायक",
      "voice_desc": "अपनी भाषा में बोलकर जानकारी प्राप्त करें। टाइप करने की जरूरत नहीं।",
      "diagnostic": "एआई निदान"
    },
    "nav": {
      "home": "मुख्य पृष्ठ",
      "check_symptoms": "बीमारी की जांच",
      "skin_care": "त्वचा जांच (Skin Check)",
      "ambulance": "एम्बुलेंस",
      "menstrual_health": "महिला स्वास्थ्य",
      "profile": "प्रोफ़ाइल",
      "offline_mode": "ऑफ़लाइन मोड",
      "offline_desc": "जांच (Symptom Check) काम कर रही है। एआई और आवाज़ के लिए इंटरनेट चाहिए।"
    },
    "roles": {
      "villager": "नागरिक",
      "ngo": "आशा",
      "admin": "प्रशासक"
    },
    "login": "लॉगिन",
    "register": "पंजीकरण",
    "logout": "लॉगआउट",
    "loginPage": {
      "left_title_1": "हर नागरिक को जोड़ना",
      "left_title_span": "गुणवत्तापूर्ण स्वास्थ्य सेवा से।",
      "left_desc": "सुरक्षित रूप से अपने मेडिकल रिकॉर्ड तक पहुंचें, पेशेवरों से परामर्श करें, और अपनी स्थानीय भाषा में आपातकालीन सहायता का अनुरोध करें।",
      "secure_private": "सुरक्षित और निजी",
      "secure_desc": "सभी स्वास्थ्य डेटा मजबूत क्लिनिकल एन्क्रिप्शन प्रोटोकॉल के तहत संरक्षित है।",
      "sign_in_desc": "कृपया अपने डैशबोर्ड तक पहुंचने के लिए साइन इन करें।",
      "select_account": "खाता प्रकार चुनें",
      "demo_patient": "डेमो नागरिक भरें",
      "demo_provider": "डेमो आशा सेविका भरें",
      "with_password": "पासवर्ड से",
      "with_otp": "ओटीपी से",
      "phone_or_email": "फोन नंबर या ईमेल",
      "password": "पासवर्ड",
      "enter_otp": "ओटीपी दर्ज करें",
      "placeholder_identifier": "उदा. 9876543210 या name@email.com",
      "forgot_password": "पासवर्ड भूल गए?",
      "placeholder_password": "••••••••",
      "placeholder_otp": "उदा. 123456",
      "get_otp": "ओटीपी प्राप्त करें",
      "secure_sign_in": "साइन इन करें",
      "authenticating": "प्रमाणीकरण हो रहा है...",
      "no_account": "क्या आपके पास खाता नहीं है?",
      "villager_sub": "मरीज़ / नागरिक",
      "ngo_sub": "स्वास्थ्य सेवा प्रदाता",
      "admin_sub": "प्रबंधन"
    },
    "registerPage": {
      "left_title_1": "हमारे भरोसेमंद स्वास्थ्य",
      "left_title_span": "नेटवर्क से जुड़ें।",
      "left_desc": "अपॉइंटमेंट बुक करने, विशेषज्ञों से चैट करने और वास्तविक समय में अपने परिवार के महत्वपूर्ण रिकॉर्ड ट्रैक करने के लिए एक खाता बनाएं।",
      "national_protocol": "राष्ट्रीय स्वास्थ्य प्रोटोकॉल",
      "national_desc": "सभी उपयोगकर्ता प्रोफ़ाइल डेटा उल्लंघनों के खिलाफ सुरक्षित हैं।",
      "set_up_account": "नैदानिक सेवाओं तक पहुंचने के लिए अपना खाता सेट करें।",
      "account_created": "खाता सफलतापूर्वक बन गया! लॉगिन पर ले जा रहे हैं...",
      "step1_role": "1. मैं पंजीकरण कर रहा हूँ...",
      "step2_personal": "2. व्यक्तिगत जानकारी",
      "full_name": "पूरा नाम",
      "choose_username": "एक उपयोगकर्ता नाम चुनें",
      "step3_contact": "3. संपर्क विवरण (कम से कम एक)",
      "phone_number": "फ़ोन नंबर",
      "email_address": "ईमेल पता",
      "step4_security": "4. सुरक्षा",
      "create_password": "एक मजबूत पासवर्ड बनाएं",
      "step5_location": "5. स्थान पहचानकर्ता",
      "village_id": "गाँव की आईडी (उदा., v101)",
      "securing_records": "रिकॉर्ड सुरक्षित किए जा रहे हैं...",
      "account_verified": "खाता सत्यापित",
      "already_have_account": "क्या आपके पास पहले से खाता है?",
      "sign_in_here": "यहां साइन इन करें",
      "gen_demo_patient": "डेमो नागरिक जनरेट करें",
      "gen_demo_provider": "डेमो आशा जनरेट करें"
    },
    "diseaseChecker": {
      "ai_axis": "स्मार्ट स्वास्थ्य जांच",
      "title": "स्वास्थ्य",
      "title_span": "जांच.",
      "sys_load": "सिस्टम: तैयार",
      "node_loc": "स्थान: वाराणसी",
      "choose_symptoms": "अपने लक्षण चुनें",
      "critical": "गंभीर",
      "common": "सामान्य",
      "describe_voice": "या स्थानीय भाषा में स्वास्थ्य स्थिति का वर्णन करें...",
      "init_scan": "जांच शुरू करें",
      "diag_await": "जांच के लिए जानकारी का इंतजार",
      "init_axis": "शुरू करने के लिए लक्षण चुनें",
      "processing": "जांच की जा रही है...",
      "local_link": "स्थानीय सहायता",
      "varanasi_node": "वाराणसी नोड V-01",
      "global_status": "वैश्विक स्थिति",
      "online_sync": "ऑनलाइन और सिंक हो रहा है",
      "download_report": "देखभाल रिपोर्ट V-01 (PDF) डाउनलोड करें",
      "fever": "तेज़ बुखार",
      "cough": "लगातार खांसी",
      "chest_pain": "सीने में तेज़ दर्द",
      "breathing": "सांस लेने में तकलीफ",
      "bleeding": "भारी रक्तस्राव",
      "headache": "तेज़ सिरदर्द",
      "vomiting": "उल्टी",
      "weakness": "बहुत कमजोरी",
      "dizziness": "चक्कर आना",
      "vision_loss": "अचानक दिखना बंद होना",
      "paralysis": "लकवा जैसे लक्षण",
      "mild_title": "सामान्य स्थिति (कम खतरा)",
      "mild_msg": "जांच के अनुसार, आपकी स्थिति गंभीर नहीं लग रही है।",
      "mild_advice": "24 घंटों तक आराम करें। यदि परेशानी बनी रहती है तो आशा कार्यकर्ता से मिलें।",
      "severe_title": "गंभीर चिकित्सा चेतावनी (SEVERE)",
      "severe_msg": "चेतावनी: महत्वपूर्ण पैटर्न विसंगति का पता चला। तत्काल क्लिनिकल हस्तक्षेप की आवश्यकता हो सकती है।",
      "severe_advice": "कृपया तुरंत निकटतम स्वास्थ्य केंद्र पर जाएं। हमने आपके स्थान के आधार पर आपातकालीन सेवाओं को सचेत कर दिया है।",
      "skin_mild_msg": "मशीन लर्निंग मॉडल द्वारा 98.4% आत्मविश्वास के साथ संभावित संपर्क डर्मेटाइटिस या फंगल संक्रमण का पता चला।",
      "skin_severe_msg": "उन्नत पैटर्न बेमेल पाया गया। संभावित गंभीर त्वचा संक्रमण या एलर्जी की प्रतिक्रिया।",
      "emergency_node": "आपातकालीन नोड",
      "init_response": "प्रतिक्रिया प्रारंभ करें",
      "voice_assist": "बोलकर बताएं",
      "start_logic": "बात करना शुरू करें",
      "remove_restart": "रद्द करें",
      "choose_imaging": "1. इमेजिंग प्रोटोकॉल",
      "support_formats": "JPG • PNG • WEBP",
      "scanner_desc": "तत्काल एआई विश्लेषण और नैदानिक मानचित्रण के लिए एक स्पष्ट नैदानिक-दृश्य फोटो अपलोड करें।",
      "privacy_axis_safe": "गोपनीयता हैंडशेक सुरक्षित",
      "privacy_desc": "छवि डेटा स्थानीय रहता है। तंत्रिका प्रसंस्करण आपके क्षेत्रीय नोड के लिए स्थानीयकृत है।",
      "processing_img": "फोटो से रोग पहचाना जाएगा",
      "take_photo": "फोटो लें",
      "take_photo_hi": "(कैमरा)",
      "upload_photo": "फोटो अपलोड करें",
      "upload_photo_hi": "(गैलरी से)",
      "drag_drop": "या यहाँ फोटो खींच कर छोड़ें",
      "privacy_main": "आपकी फोटो सुरक्षित है - केवल इस डिवाइस पर जांची जाएगी",
      "privacy_sub": "आपकी फोटो किसी को नहीं भेजी जाती।",
      "duration_q": "यह कितने समय से है?",
      "spreading_q": "क्या यह और फैल रहा है?",
      "pain_q": "क्या दर्द या जलन है?",
      "opt_started": "अभी शुरू हुआ (1-2 दिन)",
      "opt_3_7": "3 से 7 दिन",
      "opt_week": "एक हफ्ते से ज्यादा",
      "opt_no": "नहीं",
      "opt_yes": "हाँ, फैल रहा है",
      "opt_mild": "थोड़ा दर्द",
      "opt_severe": "हाँ, बहुत दर्द",
      "res_urgent_title": "आज ही स्वास्थ्य कार्यकर्ता से मिलें",
      "res_urgent_advice": "फोटो में त्वचा की सूजन के लक्षण दिख रहे हैं। कृपया तुरंत नजदीकी अस्पताल या सरकारी स्वास्थ्य केंद्र जाएं।",
      "res_moderate_title": "जल्द ही आशा कार्यकर्ता से मिलें",
      "res_moderate_advice": "फोटो में त्वचा में कुछ बदलाव दिख रहे हैं जिन पर ध्यान देने की जरूरत है। 2-3 दिन में अपने आशा कार्यकर्ता से मिलें।",
      "res_mild_title": "सामान्य त्वचा समस्या",
      "res_mild_advice": "जगह को साफ और सूखा रखें। 3-4 दिन में ठीक न हो तो आशा कार्यकर्ता से मिलें।",
      "photo_ready": "फोटो तैयार ✓",
      "retake": "फिर से फोटो लें",
      "continue_anyway": "वैसे भी आगे बढ़ें →",
      "change_photo": "फोटो बदलें",
      "analyze_photo": "फोटो की जांच करें",
      "step_photo": "फोटो",
      "step_questions": "3 प्रश्न",
      "step_result": "परिणाम",
      "question_count": "प्रश्न",
      "go_back": "पीछे जाएं",
      "download_report_txt": "स्वास्थ्य रिपोर्ट (.txt) डाउनलोड करें"
    },
    "villagerDashboard": {
      "offline_active": "ऑफ़लाइन प्रोटोकॉल सक्रिय",
      "decentralized_health": "विकेंद्रीकृत स्वास्थ्य सेवा। सत्यापित पहचान। निर्बाध देखभाल।",
      "use_without_internet": "इंटरनेट के बिना प्रयोग करें",
      "go_online": "ऑनलाइन जाएं",
      "skin_scanner": "स्किन एआई स्कैनर",
      "skin_scanner_desc": "त्वचा संक्रमण की जांच के लिए फोटो अपलोड करें।",
      "health_identity": "स्वास्थ्य पहचान",
      "health_identity_desc": "अपना क्लिनिकल इतिहास और स्वास्थ्य आईडी प्रबंधित करें।",
      "voice_assistant": "वॉइस असिस्टेंट",
      "voice_assistant_desc": "बस अपनी भाषा में बात करें। कोई टाइपिंग आवश्यक नहीं है!"
    },
    "footer": {
      "empowering": "ग्रामीण भारत को सशक्त बनाना",
      "description": "ग्रामीण भारत में महत्वपूर्ण स्वास्थ्य सेवा की खाई को पाटना। स्वस्थAI गार्जियन एआई और स्थानीय स्वास्थ्य नेटवर्क का लाभ उठाकर हर गांव में तत्काल निदान और आपातकालीन सहायता प्रदान करता है।",
      "quick_access": "त्वरित पहुँच",
      "connect": "संपर्क करें",
      "regional_hub": "क्षेत्रीय केंद्र",
      "address": "वाराणसी, उत्तर प्रदेश, भारत",
      "support_line": "सहायता लाइन",
      "emergency_helplines": "आपातकालीन हेल्पलाइन",
      "national_health_axis": "राष्ट्रीय स्वास्थ्य धुरी",
      "asha_alert": "आशा कार्यकर्ता त्वरित-अलर्ट",
      "request_assist": "स्थानीय सहायता का अनुरोध करें",
      "secured_by": "स्वस्थAI प्रोटोकॉल द्वारा सुरक्षित",
      "copyright": "© 2026 स्वस्थAI गार्जियन। AI नवाचार के माध्यम से ग्रामीण स्वास्थ्य सेवा का आधुनिकीकरण करने का एक मिशन।",
      "privacy": "गोपनीयता नीति",
      "ethics": "डिजिटल नैतिकता"
    },
    "intro": {
      "welcome_title": "स्वस्थAI में आपका स्वागत है",
      "welcome_sub": "हर गांव के लिए स्मार्ट स्वास्थ्य",
      "strategic_title": "पूरी स्वास्थ्य सहायता",
      "service_1_t": "बीमारी की जांच",
      "service_1_d": "बताएं आपको क्या तकलीफ है और तुरंत सलाह पाएं।",
      "service_2_t": "त्वचा की जांच",
      "service_2_d": "त्वचा की बीमारी जांचने के लिए फोटो खींचें।",
      "service_3_t": "एम्बुलेंस बुलाएं",
      "service_3_d": "जरूरत पड़ने पर अपने गांव में एम्बुलेंस बुलाएं।",
      "service_4_t": "गर्भवती महिला की देखभाल",
      "service_4_d": "गर्भावस्था पर नजर रखें और मां को सुरक्षित रखें।",
      "service_5_t": "बच्चे का स्वास्थ्य",
      "service_5_d": "जांचें कि आपका बच्चा स्वस्थ बढ़ रहा है या नहीं।",
      "service_6_t": "ग्राम केंद्र",
      "service_6_d": "गांव के आपातकालीन कॉल और रिकॉर्ड प्रबंधित करें।",
      "protocol_awareness": "शुरू करें",
      "select_title": "अपनी भाषा चुनें",
      "select_sub": "अपनी पसंद की भाषा चुनें।",
      "establish_sync": "शुरू करें",
      "assets_title": "हमारी मुख्य सेवाएं",
      "strategic_desc": "हर गांव के लिए तेज़ डॉक्टर सलाह और आपातकालीन सहायता।"
    },
    "dashboardExt": {
      "maternal_pulse": "मातृत्व स्वास्थ्य",
      "secure_axis": "सुरक्षित और निजी",
      "terminal_access": "खोलें",
      "my_profile": "मेरी प्रोफ़ाइल",
      "profile_desc": "अपनी स्वास्थ्य आईडी देखें, नाम और गाँव अपडेट करें।",
      "open": "खोलें",
      "skin_ai": "स्किन एआई स्कैनर",
      "skin_ai_desc": "त्वचा के संक्रमण की आसानी से जांच करें।",
      "symptom_checker": "लक्षण जांचकर्ता",
      "symptom_checker_desc": "अपने लक्षणों की जांच करें और सलाह लें।",
      "greeting": "नमस्ते, आज हम आपकी कैसे मदद कर सकते हैं?"
    },
    "menstrual": {
      "title": "महिला स्वास्थ्य",
      "safe_private": "सुरक्षित और निजी",
      "subtitle": "एआई स्वास्थ्य मार्गदर्शन, लक्षण जांच और मुफ्त पैड - पूरी तरह से निजी।",
      "emergency_help": "आपातकालीन मदद",
      "ai_assistant": "एआई सहायक",
      "symptom_check": "लक्षण जांच",
      "request_pads": "पैड मांगें",
      "health_tips": "स्वास्थ्य सुझाव",
      "request_pads_title": "सेनेटरी पैड का अनुरोध करें",
      "request_pads_desc": "आपकी आशा दीदी आपको निजी तौर पर पैड देंगी। यह अनुरोध पूरी तरह से गोपनीय है।",
      "private_note": "100% निजी — केवल आपकी आशा दीदी ही यह अनुरोध देख सकती हैं।",
      "your_village": "आपका गाँव / क्षेत्र",
      "village_placeholder": "उदा. रामपुर, सेक्टर 4",
      "request_btn": "आशा दीदी से पैड मांगें",
      "request_sent": "अनुरोध भेजा गया!",
      "request_sent_desc": "आपकी आशा दीदी को सूचित कर दिया गया है और वे जल्द ही आपसे संपर्क करेंगी।",
      "send_another": "एक और अनुरोध भेजें",
      "symptom_title": "लक्षण जांच",
      "symptom_desc": "आप जो लक्षण महसूस कर रहे हैं, उन्हें चुनें। यह निदान नहीं है - हमेशा डॉक्टर से सलाह लें।",
      "check_btn": "मेरे लक्षणों की जांच करें",
      "tips_title": "स्वास्थ्य सुझाव",
      "tips_desc": "आपके मासिक धर्म के दौरान स्वास्थ्य के लिए सरल और सिद्ध सलाह।",
      "ask_anything": "अपने स्वास्थ्य के बारे में कुछ भी पूछें...",
      "emergency_title": "आपातकालीन मदद",
      "emergency_desc": "अपनी आशा दीदी को तुरंत अलर्ट करने के लिए नीचे दिए गए बटन को दबाएं। वे आपको कॉल करेंगी और मदद के लिए आएंगी।",
      "alert_asha": "मेरी आशा दीदी को अभी अलर्ट करें",
      "call_ambulance": "108-मुफ्त एम्बुलेंस कॉल करें",
      "sakhi_welcome": "नमस्ते! मैं सखी हूँ, आपकी महिला स्वास्थ्य सहायक। मैं यहाँ मासिक धर्म स्वास्थ्य, स्वच्छता, दर्द, या डॉक्टर से कब मिलना है, इसके बारे में किसी भी प्रश्न का उत्तर देने के लिए हूँ। आप जो कुछ भी साझा करते हैं वह पूरी तरह से निजी है। मैं आज आपकी कैसे मदद कर सकती हूँ?",
      "sakhi_error": "मैं अभी आपके प्रश्न का उत्तर नहीं दे पा रही हूँ। कृपया पुनः प्रयास करें, या तत्काल सहायता के लिए अपनी आशा दीदी से संपर्क करें।",
      "sakhi_suggestions": ["मैं पीरियड के दर्द को कैसे कम करूँ?", "भारी रक्तस्राव क्या है?", "मुझे पैड कितनी बार बदलना चाहिए?", "मेरे पीरियड अनियमित हैं"],
      "sakhi_title": "सखी-एआई स्वास्थ्य सहायक",
      "live": "लाइव",
      "analyzing": "विश्लेषण हो रहा है...",
      "see_doctor": "कृपया जल्द ही डॉक्टर से मिलें",
      "see_doctor_desc": "आपके कुछ लक्षणों पर चिकित्सा ध्यान देने की आवश्यकता हो सकती है। कृपया अपनी आशा दीदी से संपर्क करें या आज ही किसी नजदीकी क्लिनिक पर जाएं।",
      "monitor": "अपने लक्षणों पर नज़र रखें",
      "monitor_desc": "ये लक्षण सामान्य हैं लेकिन नज़र रखने लायक हैं। यदि ये बने रहते हैं या बिगड़ते हैं, तो कृपया अपनी आशा दीदी से सलाह लें।",
      "doing_well": "आप ठीक लग रही हैं",
      "doing_well_desc": "कोई चिंताजनक लक्षण नहीं मिले। स्वस्थ आदतें बनाए रखें - हाइड्रेटेड रहें, आयरन से भरपूर भोजन करें और आराम करें।",
      "change_pads": "नियमित रूप से पैड बदलें",
      "change_pads_desc": "संक्रमण और गंध को रोकने के लिए हर 4-6 घंटे में अपना सैनिटरी पैड बदलें, भले ही प्रवाह हल्का हो।",
      "iron_foods": "आयरन से भरपूर भोजन करें",
      "iron_foods_desc": "पीरियड के दौरान होने वाली आयरन की कमी को पूरा करने के लिए अपने आहार में गुड़, पालक, दालें और खजूर शामिल करें।",
      "stay_active": "सक्रिय रहें और आराम करें",
      "stay_active_desc": "हल्की सैर से ऐंठन कम हो सकती है। आराम भी उतना ही महत्वपूर्ण है - अपने शरीर की सुनें और ब्रेक लें।",
      "wash_hands": "हाथ बार-बार धोएं",
      "wash_hands_desc": "बैक्टीरिया के संक्रमण को रोकने के लिए पैड बदलने से पहले और बाद में हमेशा अपने हाथों को साबुन से धोएं।",
      "offline_pad_help": "इंटरनेट नहीं है? अगर आपको तुरंत पैड चाहिए तो कृपया अपनी आशा दीदी को सीधे बताएं।",
      "sakhi_offline_help": "अभी आपके सवाल का जवाब नहीं मिल सका। कृपया फिर से कोशिश करें, या मदद के लिए आशा दीदी से मिलें।",
      "voice_not_supported": "इस फोन पर आवाज से बात करना संभव नहीं है। कृपया टाइप करें।",
      "severe_symptom_msg": "ये लक्षण गंभीर हो सकते हैं। कृपया 108 (फ्री एम्बुलेंस) पर कॉल करें या तुरंत अपनी आशा दीदी से मिलें।",
      "warning_symptom_title": "सलाह लें",
      "warning_symptom_msg": "इन लक्षणों के बारे में आज ही अपनी आशा दीदी से बात करें।",
      "safe_symptom_title": "सब ठीक है",
      "safe_symptom_msg": "कोई गंभीर लक्षण नहीं हैं। आराम करें और खूब पानी पिएं।",
      "q_heavy": "बहुत अधिक रक्तस्राव",
      "q_heavy_sub": "हर 1-2 घंटे में पैड बदलना",
      "q_pain": "पेट में तेज दर्द",
      "q_pain_sub": "दर्द जो रोज़ाना के कामों को रोक दे",
      "q_dizzy": "चक्कर आना या बेहोशी",
      "q_dizzy_sub": "कमजोरी महसूस होना",
      "q_fever": "मासिक पाळी के साथ बुखार",
      "q_fever_sub": "शरीर बहुत गर्म होना",
      "q_irregular": "अनियमित माहवारी",
      "q_irregular_sub": "समय पर माहवारी न आना",
      "q_clots": "खून के बड़े थक्के",
      "q_clots_sub": "बड़े थक्के निकलना"
    },
    "ambulance": {
      "title": "आपातकालीन बचाव",
      "subtitle": "एम्बुलेंस या स्वास्थ्य कर्मी चाहिए? नीचे क्लिक करें। आपका स्थान स्वचालित रूप से साझा किया जाता है।",
      "request_team": "आपातकालीन टीम बुलाएं",
      "non_critical": "सामान्य चिकित्सा परिवहन",
      "rescue_dispatched": "बचाव टीम भेजी गई",
      "call_driver": "ड्राइवर को कॉल करें",
      "dispatching": "भेजा जा रहा है...",
      "patient_name": "मरीज का नाम",
      "contact_number": "मोबाइल नंबर",
      "emergency_type": "आपातकाल का प्रकार",
      "location": "आपकी लोकेशन",
      "accident": "सड़क दुर्घटना",
      "accident_hi": "",
      "pregnancy": "प्रसव पीड़ा",
      "pregnancy_hi": "",
      "heart": "दिल का दौरा",
      "heart_hi": "",
      "respiratory": "सांस की तकलीफ",
      "respiratory_hi": "",
      "trauma": "गंभीर चोट",
      "trauma_hi": "",
      "general": "सामान्य आपातकाल",
      "general_hi": "",
      "no_time": "फॉर्म भरने का समय नहीं है?",
      "sos_desc": "इस बटन को दबाएं। हम आपके फोन के जीपीएस का उपयोग करके आपको ढूंढ लेंगे और तुरंत नजदीकी एम्बुलेंस भेजेंगे।",
      "sos_btn": "SOS — अभी मदद भेजें"
    },
    "symptom": {
      "title": "एआई लक्षण जांचकर्ता",
      "subtitle": "हमें बताएं कि आप कैसा महसूस कर रहे हैं। हम आपको बताएंगे कि आगे क्या करना है।",
      "select_symptoms": "अपने लक्षण चुनें:",
      "check_now": "अभी जांचें",
      "fever": "बुखार",
      "cough": "खांसी",
      "chest_pain": "सीने में दर्द",
      "breathing": "सांस लेने में तकलीफ",
      "bleeding": "खून आना",
      "headache": "सिरदर्द",
      "vomiting": "उल्टी",
      "weakness": "कमजोरी",
      "analyzing": "विश्लेषण कर रहा है...",
      "go_hospital": "तुरंत अस्पताल जाएं",
      "see_doctor": "आज ही डॉक्टर से मिलें",
      "mild": "हल्का — घर पर आराम करें"
    }
  },
  "en": {
    "dashboard": "Patient Dashboard",
    "welcome_back": "Welcome back. How can we help you today?",
    "network_connected": "Network Connected",
    "swasthai": "SwasthAI",
    "national_impact": "National Health Impact",
    "tagline": "We help you get doctor advice and medical help quickly, even without internet.",
    "portal_access": "Access Portal",
    "join_network": "Join Network",
    "citizens_covered": "Citizens Covered",
    "network_uptime": "Network Uptime",
    "villages_reached": "Villages Reached",
    "everything_you_need": "Everything You Need",
    "for_good_health": "for Good Health",
    "get_started_now": "Get Started Now",
    "ready_to_transform": "Ready to Transform Rural Health?",
    "join_thousands": "Join thousands of ASHA workers, doctors, and citizens building the future of comprehensive healthcare infrastructure.",
    "footer_text": "© 2026 SwasthAI Healthcare Platform. All Rights Reserved. IEEE Certified.",
    "services": {
      "maternal": "Maternal Health Portal",
      "maternal_desc": "Access discrete clinical guidance, track menstrual cycles, and receive dedicated maternal support.",
      "access_portal": "Access Portal",
      "symptoms": "Smart Symptom Checker",
      "symptoms_desc": "Check your illness using our smart tool.",
      "how_feeling": "Tell us how you are feeling:",
      "check_symptoms": "Check Symptoms",
      "analyzing": "Analyzing...",
      "emergency": "Emergency Hub",
      "immediate_assist": "Immediate assistance",
      "ambulance_desc": "Need urgent medical help? Request an ambulance or alert a local ASHA worker immediately.",
      "request_ambulance": "Request Ambulance",
      "dispatching": "Dispatching...",
      "teleclinic": "Talk to Doctor (Video)",
      "tele_desc": "Talk to city doctors instantly through video calls.",
      "academy": "Health Info",
      "academy_desc": "Learn how to stay healthy and prevent illness.",
      "voice": "Speak to Get Help",
      "voice_desc": "No need to type, just speak and get help.",
      "diagnostic": "Diagnostic AI"
    },
    "nav": {
      "home": "Home",
      "services": "Services",
      "about": "About Us",
      "profile": "Profile",
      "dashboard": "Dashboard",
      "check_symptoms": "Check Symptoms",
      "skin_care": "Skin Care",
      "ambulance": "Ambulance",
      "menstrual_health": "Menstrual Health",
      "offline_mode": "Offline Mode",
      "offline_desc": "Symptom Checker works. Voice & AI need internet."
    },
    "logout": "Sign Out",
    "save": "SAVE",
    "cancel": "CANCEL",
    "verified": "VERIFIED",
    "roles": {
      "villager": "Patient",
      "ngo": "ASHA",
      "admin": "Admin"
    },
    "login": "Sign In",
    "register": "Create Account",
    "loginPage": {
      "left_title_1": "Connecting every citizen to",
      "left_title_span": "quality healthcare.",
      "left_desc": "Securely access your medical records, consult with professionals, and request emergency assistance in your local language.",
      "secure_private": "Secure & Private",
      "secure_desc": "All health data is protected under robust clinical encryption protocols and only accessible by authorized healthcare providers.",
      "sign_in_desc": "Please sign in to access your dashboard.",
      "select_account": "Select Account Type",
      "demo_patient": "Fill Demo Patient",
      "demo_provider": "Fill Demo Provider",
      "with_password": "With Password",
      "with_otp": "With OTP",
      "phone_or_email": "Phone Number or Email",
      "password": "Password",
      "enter_otp": "Enter OTP",
      "placeholder_identifier": "e.g. 9876543210 or name@email.com",
      "forgot_password": "Forgot password?",
      "placeholder_password": "••••••••",
      "placeholder_otp": "e.g. 123456",
      "get_otp": "Get OTP",
      "secure_sign_in": "Secure Sign In",
      "authenticating": "Authenticating...",
      "no_account": "Don't have an account?",
      "villager_sub": "Patient / Citizen",
      "ngo_sub": "Healthcare Provider",
      "admin_sub": "Management"
    },
    "registerPage": {
      "left_title_1": "Join our trusted",
      "left_title_span": "healthcare network.",
      "left_desc": "Create an account to securely book appointments, chat with specialists, and track your family's vital records in real-time.",
      "national_protocol": "National Health Protocol",
      "national_desc": "All user profiles are authenticated according to national privacy guidelines to ensure a zero-tolerance policy against data breaches.",
      "set_up_account": "Set up your account to access all clinical services.",
      "account_created": "Account Created Successfully! Redirecting to login...",
      "step1_role": "1. I am registering as a...",
      "step2_personal": "2. Personal Information",
      "full_name": "Full Name",
      "choose_username": "Choose a Username",
      "step3_contact": "3. Contact Details (At least one)",
      "phone_number": "Phone Number",
      "email_address": "Email Address",
      "step4_security": "4. Security",
      "create_password": "Create a password",
      "step5_location": "5. Location Identifier",
      "village_id": "Village ID (e.g., v101)",
      "securing_records": "Securing Records...",
      "account_verified": "Account Verified",
      "already_have_account": "Already have an account?",
      "sign_in_here": "Sign In Here",
      "gen_demo_patient": "Generate Demo Patient",
      "gen_demo_provider": "Generate Demo Provider"
    },
    "diseaseChecker": {
      "ai_axis": "SMART HEALTH CHECK",
      "title": "Health",
      "title_span": "Check.",
      "sys_load": "System: Ready",
      "node_loc": "Location: Varanasi",
      "choose_symptoms": "Choose your symptoms",
      "critical": "CRITICAL",
      "common": "COMMON",
      "describe_voice": "Or describe health condition in local language...",
      "init_scan": "Start Health Check",
      "diag_await": "Waiting for information",
      "init_axis": "Choose symptoms to start",
      "processing": "Checking symptoms...",
      "local_link": "Local Help",
      "varanasi_node": "Varanasi Node V-01",
      "global_status": "Global Status",
      "online_sync": "Online & Syncing",
      "download_report": "DOWNLOAD CARE REPORT V-01 (PDF)",
      "fever": "High Fever",
      "cough": "Continuous Cough",
      "chest_pain": "Severe Chest Pain",
      "breathing": "Difficulty Breathing",
      "bleeding": "Heavy Bleeding",
      "headache": "Strong Headache",
      "vomiting": "Vomiting",
      "weakness": "Extreme Weakness",
      "dizziness": "Dizziness",
      "vision_loss": "Sudden Vision Loss",
      "paralysis": "Sudden Weakness in One Side",
      "mild_title": "Condition is Mild",
      "mild_msg": "Based on our check, your condition does not look serious.",
      "mild_advice": "Rest for 24 hours. If you still feel bad, see an ASHA worker.",
      "severe_title": "Urgent Medical Alert",
      "severe_msg": "Warning: Your symptoms look serious. You need to see a doctor now.",
      "severe_advice": "Please go to the nearest hospital immediately. We have sent an alert to help you.",
      "skin_mild_msg": "This looks like a common skin infection.",
      "skin_severe_msg": "Advanced pattern mismatch found. Potential severe skin infection or an allergic reaction.",
      "emergency_node": "Emergency Node",
      "init_response": "Initialize Response",
      "voice_assist": "Speak to App",
      "start_logic": "Start Speaking",
      "remove_restart": "Cancel",
      "choose_imaging": "1. Imaging Protocol",
      "support_formats": "JPG • PNG • WEBP",
      "scanner_desc": "Upload a clear clinical-view photo for instant AI analysis and diagnostic mapping.",
      "privacy_axis_safe": "Privacy Handshake Safe",
      "privacy_desc": "Image data remains local. Neural processing is localized to your regional node.",
      "processing_img": "Photo is analyzed for redness & inflammation",
      "take_photo": "Take Photo",
      "take_photo_hi": "(Camera)",
      "upload_photo": "Upload Photo",
      "upload_photo_hi": "(Gallery)",
      "drag_drop": "Or drag & drop a photo here",
      "privacy_main": "Your photo stays private — analyzed only on this device",
      "privacy_sub": "Your photo is not sent to anyone.",
      "duration_q": "How long have you had this?",
      "spreading_q": "Is it spreading to other areas?",
      "pain_q": "Is there pain or burning?",
      "opt_started": "Just started (1-2 days)",
      "opt_3_7": "3 to 7 days",
      "opt_week": "More than a week",
      "opt_no": "No",
      "opt_yes": "Yes, spreading",
      "opt_mild": "A little",
      "opt_severe": "Yes, painful",
      "res_urgent_title": "Visit Health Worker Today",
      "res_urgent_advice": "The photo shows signs of skin inflammation. Please visit your nearest primary health centre immediately.",
      "res_moderate_title": "Visit ASHA Worker Soon",
      "res_moderate_advice": "The photo shows some skin changes that need attention. Visit your nearby PHC or ASHA worker within 2-3 days.",
      "res_mild_title": "Mild Skin Issue",
      "res_mild_advice": "Keep the area clean and dry. If it does not improve in 3-4 days, please see an ASHA worker.",
      "photo_ready": "Photo Ready ✓",
      "retake": "Retake Photo",
      "continue_anyway": "Continue Anyway →",
      "change_photo": "Change Photo",
      "analyze_photo": "Analyze Photo",
      "step_photo": "Photo",
      "step_questions": "3 Questions",
      "step_result": "Result",
      "question_count": "Question",
      "go_back": "Go Back",
      "download_report_txt": "Download Health Report (.txt)"
    },
    "villagerDashboard": {
      "offline_active": "Offline Protocol Active",
      "decentralized_health": "Decentralized Healthcare. Verified Identity. Seamless Care.",
      "use_without_internet": "Use Without Internet",
      "go_online": "Go Online",
      "skin_scanner": "Skin AI Scanner",
      "skin_scanner_desc": "Upload photos to check for skin infections or rashes with Deep Learning.",
      "health_identity": "Health Identity",
      "health_identity_desc": "Manage your clinical history, Health ID, and secure device nodes.",
      "voice_assistant": "Voice Assistant",
      "voice_assistant_desc": "Just speak to the app in your language. No typing needed at all!"
    },
    "footer": {
      "empowering": "Empowering Rural Bharat",
      "description": "Bridging the critical healthcare gap in rural India. SwasthAI Guardian leverages AI and local health networks to provide instant diagnostics and emergency support to every village.",
      "quick_access": "Quick Access",
      "connect": "Connect",
      "regional_hub": "Regional Hub",
      "address": "Varanasi, Uttar Pradesh, India",
      "support_line": "Support Line",
      "emergency_helplines": "Emergency Helplines",
      "national_health_axis": "National Health Axis",
      "asha_alert": "ASHA Worker Quick-Alert",
      "request_assist": "Request Local Assistance",
      "secured_by": "Secured by SwasthAI Protocols",
      "copyright": "© 2026 SwasthAI Guardian. A mission to modernize rural healthcare through AI innovation.",
      "privacy": "Privacy Policy",
      "ethics": "Digital Ethics"
    },
    "intro": {
      "welcome_title": "Welcome to SwasthAI",
      "welcome_sub": "Smart Healthcare for Every Village",
      "strategic_title": "Complete Health Support",
      "service_1_t": "Check Symptoms",
      "service_1_d": "Tell us how you feel and get instant advice.",
      "service_2_t": "Skin Scan",
      "service_2_d": "Take a photo to check for skin infections.",
      "service_3_t": "Call Ambulance",
      "service_3_d": "Get an ambulance to your village quickly.",
      "service_4_t": "Mother's Health",
      "service_4_d": "Track pregnancy and keep mothers safe.",
      "service_5_t": "Child Health",
      "service_5_d": "Check if your child is growing healthy and strong.",
      "service_6_t": "Village Center",
      "service_6_d": "Manage emergency calls and village records.",
      "protocol_awareness": "Get Started",
      "select_title": "Choose Your Language",
      "select_sub": "Choose the language you like.",
      "establish_sync": "Continue",
      "assets_title": "Our Key Services",
      "strategic_desc": "Fast doctor advice and emergency help for every village."
    },
    "dashboardExt": {
      "maternal_pulse": "Maternal Health",
      "secure_axis": "Private & Secure",
      "terminal_access": "Open Access",
      "my_profile": "My Profile",
      "profile_desc": "View your health ID, update your name and village.",
      "open": "Open",
      "skin_ai": "Skin AI Scanner",
      "skin_ai_desc": "Check skin infections easily.",
      "symptom_checker": "AI Symptom Checker",
      "symptom_checker_desc": "Check your symptoms and get advice.",
      "greeting": "Hello, how can we help you today?"
    },
    "menstrual": {
      "title": "Women's Health",
      "safe_private": "Safe & Private",
      "subtitle": "AI-powered health guidance, symptom checking, and free pad access - completely private and confidential.",
      "emergency_help": "Emergency Help",
      "ai_assistant": "AI Assistant",
      "symptom_check": "Symptom Check",
      "request_pads": "Request Pads",
      "health_tips": "Health Tips",
      "request_pads_title": "Request Sanitary Pads",
      "request_pads_desc": "Your ASHA worker will deliver pads privately to your location. This request is completely confidential.",
      "private_note": "100% Private — Only your assigned ASHA worker can see this request. No one else will know.",
      "your_village": "Your Village / Area",
      "village_placeholder": "e.g. Rampur, Sector 4",
      "request_btn": "Request Pads from ASHA Worker",
      "request_sent": "Request Sent!",
      "request_sent_desc": "Your ASHA worker has been notified and will contact you shortly.",
      "send_another": "Send Another Request",
      "symptom_title": "Symptom Check",
      "symptom_desc": "Select any symptoms you are currently experiencing. This is not a diagnosis - always consult a doctor for medical advice.",
      "check_btn": "Check My Symptoms",
      "tips_title": "Health Tips",
      "tips_desc": "Simple, proven advice for your health and wellbeing during your period.",
      "ask_anything": "Ask me anything about your health...",
      "emergency_title": "Emergency Help",
      "emergency_desc": "Press the button below to immediately alert your ASHA worker. She will call you and come to help.",
      "alert_asha": "Alert My ASHA Worker Now",
      "call_ambulance": "Call 108-Free Ambulance",
      "offline_pad_help": "No Internet? Please tell your ASHA worker directly if you need pads immediately.",
      "sakhi_offline_help": "I could not process your question right now. Please try again, or contact your ASHA worker for immediate help.",
      "voice_not_supported": "Voice input is not supported on this device. Please type your message.",
      "severe_symptom_msg": "These symptoms could be serious. Please call 108 (Free Ambulance) or find your ASHA worker immediately.",
      "warning_symptom_title": "Seek Advice",
      "warning_symptom_msg": "These symptoms should be discussed with your ASHA worker today.",
      "safe_symptom_title": "Doing Well",
      "safe_symptom_msg": "No urgent symptoms. Remember to rest and drink plenty of water.",
      "q_heavy": "Very heavy bleeding",
      "q_heavy_sub": "Changing pad every 1-2 hours",
      "q_pain": "Severe abdominal pain",
      "q_pain_sub": "Pain that stops daily activities",
      "q_dizzy": "Dizziness or fainting",
      "q_dizzy_sub": "Feeling lightheaded or weak",
      "q_fever": "Fever with periods",
      "q_fever_sub": "Temperature above 38°C",
      "q_irregular": "Irregular or missed periods",
      "q_irregular_sub": "Cycle shorter than 21 or longer than 35 days",
      "q_clots": "Large blood clots",
      "q_clots_sub": "Clots larger than a coin"
    },
    "ambulance": {
      "title": "Emergency Rescue",
      "subtitle": "Need an ambulance or health responder? Click below. Your location is automatically shared.",
      "request_team": "Request Emergency Team",
      "non_critical": "Non-Critical Medical Transport",
      "rescue_dispatched": "RESCUE DISPATCHED",
      "call_driver": "Call Driver",
      "dispatching": "Dispatching...",
      "patient_name": "Patient Name",
      "contact_number": "Contact Number",
      "emergency_type": "Emergency Type",
      "location": "Location",
      "accident": "Road Accident",
      "accident_hi": "",
      "pregnancy": "Pregnancy Case",
      "pregnancy_hi": "",
      "heart": "Heart Attack",
      "heart_hi": "",
      "respiratory": "Breathing Issue",
      "respiratory_hi": "",
      "trauma": "Physical Injury",
      "trauma_hi": "",
      "general": "Other Emergency",
      "general_hi": "",
      "no_time": "No time to fill form?",
      "sos_desc": "Press this button. We will use your phone's GPS to find you and dispatch the nearest ambulance instantly.",
      "sos_btn": "SOS — Send Help Now"
    },
    "symptom": {
      "title": "AI Symptom Checker",
      "subtitle": "Tell us how you feel. We will guide you on what to do next.",
      "select_symptoms": "Select your symptoms:",
      "check_now": "Check Now",
      "fever": "Fever",
      "cough": "Cough",
      "chest_pain": "Chest Pain",
      "breathing": "Breathing Difficulty",
      "bleeding": "Bleeding",
      "headache": "Headache",
      "vomiting": "Vomiting",
      "weakness": "Weakness",
      "analyzing": "Analyzing...",
      "go_hospital": "GO TO HOSPITAL NOW",
      "see_doctor": "SEE A DOCTOR TODAY",
      "mild": "MILD — Monitor at Home"
    }
  },
  "mr": {
    "dashboard": "रुग्ण डॅशबोर्ड",
    "welcome_back": "स्वागत आहे. आम्ही तुम्हाला कशी मदत करू शकतो?",
    "network_connected": "नेटवर्क जोडले",
    "swasthai": "स्वस्थAI",
    "national_impact": "राष्ट्रीय आरोग्य प्रभाव",
    "tagline": "आम्ही एआय डायग्नोस्टिक्स, ऑफलाइन सिनर्जी आणि समर्पित आरोग्य कर्मचाऱ्यांद्वारे दूरच्या गावांना जागतिक दर्जाच्या वैद्यकीय सुविधांशी जोडतो.",
    "portal_access": "पोर्टल उघडा",
    "join_network": "नेटवर्कमध्ये सामील व्हा",
    "citizens_covered": "नागरिक कव्हर केले",
    "network_uptime": "नेटवर्क अपटाइम",
    "villages_reached": "गावांपर्यंत पोहोचले",
    "everything_you_need": "चांगल्या आरोग्यासाठी",
    "for_good_health": "सर्व काही",
    "get_started_now": "आत्ताच सुरू करा",
    "ready_to_transform": "ग्रामीण आरोग्य बदलण्यासाठी तयार आहात?",
    "join_thousands": "भविष्यासाठी आरोग्य उभारण्यात हजारो आशा कार्यकर्त्यांसह सामील व्हा.",
    "footer_text": "© 2026 स्वस्थAI हेल्थकेअर प्लॅटफॉर्म। सर्व हक्क राखीव. IEEE प्रमाणित.",
    "services": {
      "maternal": "मातृ आरोग्य केंद्र",
      "maternal_desc": "मासिक पाळी ट्रॅकिंग आणि सुरक्षित मार्गदर्शन मिळवा.",
      "access_portal": "पोर्टल उघडा",
      "symptoms": "स्मार्ट निदान",
      "symptoms_desc": "एआय समर्थित प्राथमिक निदान",
      "how_feeling": "तुम्हाला कसे वाटत অংশে?",
      "check_symptoms": "लक्षणे तपासा",
      "analyzing": "विश्लेषण करत आहे...",
      "emergency": "आणीबाणी केंद्र",
      "immediate_assist": "तात्काळ मदत",
      "ambulance_desc": "रुग्णवाहिका किंवा आशा कार्यकर्त्याला त्वरित बोलावा. तुमचे स्थान आपोआप शेअर केले जाईल.",
      "request_ambulance": "रुग्णवाहिकेला बोलावा",
      "dispatching": "पाठवत आहे...",
      "teleclinic": "टेली-मेडिसिन",
      "tele_desc": "शहरातील तज्ञ डॉक्टरांशी व्हिडिओ कॉल करा.",
      "academy": "आरोग्य माहिती",
      "academy_desc": "रोग प्रतिबंध आणि पोषण माहिती.",
      "voice": "आवाज साहाय्यक",
      "voice_desc": "माहिती मिळवण्यासाठी फक्त बोला. टायपिंगची गरज नाही.",
      "diagnostic": "एआय निदान"
    },
    "nav": {
      "home": "मुख्यपृष्ठ",
      "services": "सेवाएं",
      "about": "आमच्याबद्दल",
      "profile": "प्रोफाइल",
      "dashboard": "डॅशबोर्ड",
      "check_symptoms": "लक्षणे तपासा",
      "skin_care": "त्वचेची काळजी",
      "ambulance": "रुग्णवाहिका",
      "menstrual_health": "मासिक पाळी आरोग्य",
      "offline_mode": "ऑफलाइन मोड",
      "offline_desc": "लक्षण तपासणी सुरू आहे. एआय आणि व्हॉइससाठी इंटरनेट आवश्यक आहे."
    },
    "logout": "लॉगआउट",
    "save": "जतन करा",
    "cancel": "रद्द करा",
    "verified": "सत्यापित",
    "roles": {
      "villager": "नागरिक",
      "ngo": "आशा",
      "admin": "प्रशासक"
    },
    "login": "लॉगिन",
    "register": "नोंदणी",
    "loginPage": {
      "left_title_1": "प्रत्येक नागरिकाला जोडत आहे",
      "left_title_span": "उत्तम आरोग्य सेवेसाठी.",
      "left_desc": "आपल्या वैद्यकीय रेकॉर्डमध्ये सुरक्षितपणे प्रवेश करा, आणि स्थानिक भाषेत आपत्कालीन मदत घ्या.",
      "secure_private": "सुरक्षित आणि खाजगी",
      "secure_desc": "सर्व आरोग्य डेटा एन्क्रिप्शन प्रोटोकॉल अंतर्गत संरक्षित आहे.",
      "sign_in_desc": "डॅशबोर्डवर जाण्यासाठी साइन इन करा.",
      "select_account": "खाता प्रकार निवडा",
      "demo_patient": "डेमो रुग्ण भरा",
      "demo_provider": "डेमो आशा सेविका भरा",
      "with_password": "पासवर्डसह",
      "with_otp": "OTP सह",
      "phone_or_email": "फोन नंबर किंवा ईमेल",
      "password": "पासवर्ड",
      "enter_otp": "OTP प्रविष्ट करा",
      "placeholder_identifier": "उदा. 9876543210",
      "forgot_password": "पासवर्ड विसरलात?",
      "placeholder_password": "••••••••",
      "placeholder_otp": "उदा. 123456",
      "get_otp": "OTP मिळवा",
      "secure_sign_in": "साइन इन करा",
      "authenticating": "प्रमाणीकरण होत आहे...",
      "no_account": "तुमचे खाते नाही का?",
      "villager_sub": "रुग्ण / नागरिक",
      "ngo_sub": "आरोग्य सेवा प्रदाता",
      "admin_sub": "व्यवस्थापन"
    },
    "registerPage": {
      "left_title_1": "आमच्या विश्वसनीय आरोग्य",
      "left_title_span": "नेटवर्कमध्ये सामील व्हा.",
      "left_desc": "अपॉइंटमेंट बुक करण्यासाठी आणि कुटुंबाच्या नोंदी ठेवण्यासाठी खाते तयार करा.",
      "national_protocol": "राष्ट्रीय आरोग्य प्रोटोकॉल",
      "national_desc": "सर्व वापरकर्ता प्रोफाइल सुरक्षित आहेत.",
      "set_up_account": "आपले खाते सेट अप करा.",
      "account_created": "खाते यशस्वीरित्या तयार झाले! लॉगिनवर घेऊन जात आहे...",
      "step1_role": "1. मी म्हणून नोंदणी करत आहे...",
      "step2_personal": "2. वैयक्तिक माहिती",
      "full_name": "पूर्ण नाव",
      "choose_username": "वापरकर्तानाव निवडा",
      "step3_contact": "3. संपर्क तपशील",
      "phone_number": "फोन नंबर",
      "email_address": "ईमेल पत्ता",
      "step4_security": "4. सुरक्षा",
      "create_password": "मजबूत पासवर्ड तयार करा",
      "step5_location": "5. स्थान आयडी",
      "village_id": "गाव ओळख (उदा. v101)",
      "securing_records": "रेकॉर्ड सुरक्षित करत आहे...",
      "account_verified": "खाते सत्यापित",
      "already_have_account": "आधीच खाते आहे का?",
      "sign_in_here": "येथे साइन इन करा",
      "gen_demo_patient": "डेमो रुग्ण तयार करा",
      "gen_demo_provider": "डेमो सेवा देणारा तयार करा"
    },
    "diseaseChecker": {
      "ai_axis": "AI डायग्नोस्टिक ॲक्सिस V-02",
      "title": "रोग",
      "title_span": "तपासणी.",
      "sys_load": "सिस्टीम लोड: स्थिर",
      "node_loc": "नोड: वाराणसी सेंट्रल",
      "choose_symptoms": "लक्षणे निवडा",
      "critical": "गंभीर",
      "common": "सामान्य",
      "describe_voice": "किंवा स्थानिक भाषेत प्रकृतीचे वर्णन करा...",
      "init_scan": "स्कॅन प्रोटोकॉल सुरू करा",
      "diag_await": "निदानात्मक डेटाची प्रतीक्षा",
      "init_axis": "गणना करण्यासाठी डावा अक्ष सुरू करा",
      "processing_img": "फोटोवरून त्वचा रोगाचे निदान होईल",
      "local_link": "स्थानिक लिंक",
      "varanasi_node": "वाराणसी नोड V-01",
      "global_status": "जागतिक स्थिती",
      "online_sync": "ऑनलाइन आणि सिंक होत आहे",
      "download_report": "काळजी अहवाल V-01 (PDF) डाउनलोड करा",
      "fever": "तीव्र ताप",
      "cough": "सतत खोकला",
      "chest_pain": "छातीत तीव्र वेदना",
      "breathing": "श्वास घेण्यास त्रास",
      "bleeding": "तीव्र रक्तस्त्राव",
      "headache": "तीव्र डोकेदुखी",
      "vomiting": "उलट्या",
      "weakness": "अत्यंत अशक्तपणा",
      "dizziness": "चक्कर येणे",
      "vision_loss": "अचानक दृष्टी जाणे",
      "paralysis": "एका बाजूला अचानक अशक्तपणा"
    },
    "villagerDashboard": {
      "offline_active": "ऑफलाइन प्रोटोकॉल सक्रिय",
      "decentralized_health": "विकेंद्रित आरोग्य सेवा. अखंड काळजी.",
      "use_without_internet": "इंटरनेटशिवाय वापरा",
      "go_online": "ऑनलाइन जा",
      "skin_scanner": "स्किन एआय स्कॅनर",
      "skin_scanner_desc": "त्वचेचे संक्रमण तपासण्यासाठी फोटो अपलोड करा.",
      "health_identity": "आरोग्य ओळख",
      "health_identity_desc": "तुमचा इतिहास आणि आरोग्य आयडी व्यवस्थापित करा.",
      "voice_assistant": "व्हॉइस असिस्टंट",
      "voice_assistant_desc": "फक्त बोला, टायपिंगची गरज नाही!"
    },
    "footer": {
      "empowering": "ग्रामीण भारताचे सक्षमीकरण",
      "description": "ग्रामीण भारतातील गंभीर आरोग्य सेवा तफावत दूर करणे. स्वस्थAI गार्जियन एआय आणि स्थानिक आरोग्य नेटवर्कचा वापर करून प्रत्येक गावाला त्वरित निदान आणि आपत्कालीन मदत पुरवते.",
      "quick_access": "क्विक ऍक्सेस",
      "connect": "संपर्क करा",
      "regional_hub": "प्रादेशिक केंद्र",
      "address": "वाराणसी, उत्तर प्रदेश, भारत",
      "support_line": "सपोर्ट लाईन",
      "emergency_helplines": "आपत्कालीन हेल्पलाइन",
      "national_health_axis": "राष्ट्रीय आरोग्य अक्ष",
      "asha_alert": "आशा कार्यकर्ता क्विक-अलर्ट",
      "request_assist": "स्थानिक मदतीची विनंती करा",
      "secured_by": "स्वस्थAI प्रोटोकॉलद्वारे सुरक्षित",
      "copyright": "© 2026 स्वस्थAI गार्जियन. एआय इनोव्हेशनद्वारे ग्रामीण आरोग्य सेवा आधुनिक करण्याचे ध्येय.",
      "privacy": "गोपनीयता धोरण",
      "ethics": "डिजिटल नीतिमत्ता"
    },
    "intro": {
      "welcome_title": "स्वस्थAI गार्जियनमध्ये आपले स्वागत आहे",
      "welcome_sub": "ग्रामीण आरोग्य सेवेचे भविष्य येथे आहे. ऑफलाइन-तयार आणि एआई-चालित.",
      "strategic_title": "धोरणात्मक आरोग्य देखरेख",
      "service_1_t": "स्मार्ट एआई निदान",
      "service_1_d": "ऑफलाइन-सक्षम एआई नोड्स वापरून त्वरित आरोग्य मूल्यमापन मिळवा.",
      "service_2_t": "आणीबाणी प्रोटोकॉल",
      "service_2_d": "क्रिटिकल केअरसाठी वन-टॅप रुग्णवाहिका डिस्पॅच आणि आशा कार्यकर्ता सूचना.",
      "service_3_t": "माता आणि मासिक पाळी केंद्र",
      "service_3_d": "महिलांच्या आरोग्यासाठी सुरक्षित, खाजगी ट्रॅकिंग आणि क्लिनिकल मार्गदर्शन.",
      "service_4_t": "टेली-हेल्थ ब्रिज",
      "service_4_d": "शहरी तज्ञांशी थेट उच्च-कॉम्प्रेशन व्हिडिओ/ऑडिओ सल्लामसलत.",
      "service_5_t": "विकेंद्रित आरोग्य आयडी",
      "service_5_d": "तुमच्या संपूर्ण कुटुंबासाठी डिजिटल मेडिकल रेकॉर्ड एका सुरक्षित ठिकाणी व्यवस्थापित करा.",
      "service_6_t": "स्किन एआई स्कॅनर",
      "service_6_d": "त्वचेचे संक्रमण आणि परिस्थितींचे त्वरित क्लिनिकल-ग्रेड विश्लेषण.",
      "protocol_awareness": "पुढील: प्रोटोकॉल जागरूकता",
      "select_title": "तुमची भाषा निवडा",
      "select_sub": "उत्तम अनुभवासाठी कृपया तुमची पसंतीची भाषा निवडा.",
      "establish_sync": "सिंक स्थापित करा"
    },
    "dashboardExt": {
      "maternal_pulse": "मातृत्व आरोग्य",
      "secure_axis": "सुरक्षित आणि खाजगी",
      "terminal_access": "उघडा",
      "my_profile": "माझी प्रोफाईल",
      "profile_desc": "तुमचा हेल्थ आयडी पहा, नाव आणि गाव अपडेट करा.",
      "open": "उघडा",
      "skin_ai": "त्वचा एआय स्कॅनर",
      "skin_ai_desc": "त्वचेच्या संसर्गाची सहज तपासणी करा.",
      "symptom_checker": "लक्षणे तपासक",
      "symptom_checker_desc": "तुमची लक्षणे तपासा आणि सल्ला मिळवा.",
      "greeting": "नमस्कार, आज आम्ही तुम्हाला कशी मदत करू शकतो?"
    },
    "menstrual": {
      "title": "महिला आरोग्य",
      "safe_private": "सुरक्षित आणि खाजगी",
      "subtitle": "एआय आरोग्य मार्गदर्शन, लक्षणे तपासणी आणि मोफत पॅड - पूर्णपणे खाजगी.",
      "emergency_help": "आपत्कालीन मदत",
      "ai_assistant": "एआय असिस्टंट",
      "symptom_check": "लक्षणे तपासणी",
      "request_pads": "पॅडची विनंती करा",
      "health_tips": "आरोग्य टिप्स",
      "request_pads_title": "सॅनिटरी पॅडची विनंती करा",
      "request_pads_desc": "तुमच्या आशा ताई तुम्हाला खाजगीरित्या पॅड देतील. ही विनंती पूर्णपणे गोपनीय आहे.",
      "private_note": "100% खाजगी — फक्त तुमच्या आशा ताई ही विनंती पाहू शकतात.",
      "your_village": "तुमचे गाव / क्षेत्र",
      "village_placeholder": "उदा. रामपूर, सेक्टर 4",
      "request_btn": "आशा ताईंकडून पॅडची विनंती करा",
      "request_sent": "विनंती पाठवली!",
      "request_sent_desc": "तुमच्या आशा ताईंना सूचित केले आहे आणि त्या लवकरच तुमच्याशी संपर्क साधतील.",
      "send_another": "आणखी एक विनंती पाठवा",
      "symptom_title": "लक्षणे तपासणी",
      "symptom_desc": "तुम्हाला जाणवणारी कोणतीही लक्षणे निवडा. हे निदान नाही - नेहमी डॉक्टरांचा सल्ला घ्या.",
      "check_btn": "माझी लक्षणे तपासा",
      "tips_title": "आरोग्य टिप्स",
      "tips_desc": "मासिक पाळी दरम्यान तुमच्या आरोग्यासाठी सोपा आणि सिद्ध सल्ला.",
      "ask_anything": "तुमच्या आरोग्याबद्दल काहीही विचारा...",
      "emergency_title": "आपत्कालीन मदत",
      "emergency_desc": "तुमच्या आशा ताईंना त्वरित सतर्क करण्यासाठी खालील बटण दाबा. त्या तुम्हाला कॉल करतील आणि मदतीला येतील.",
      "alert_asha": "माझ्या आशा ताईंना आता सतर्क करा",
      "call_ambulance": "108-मोफत रुग्णवाहिका कॉल करा"
    },
    "ambulance": {
      "title": "आपत्कालीन बचाव",
      "subtitle": "रुग्णवाहिका किंवा आरोग्य कर्मचारी हवा आहे का? खाली क्लिक करा. तुमचे स्थान स्वयंचलितपणे सामायिक केले जाते.",
      "request_team": "आपत्कालीन टीमची विनंती करा",
      "non_critical": "सामान्य वैद्यकीय वाहतूक",
      "rescue_dispatched": "बचाव टीम पाठवली",
      "call_driver": "ड्रायव्हरला कॉल करा",
      "dispatching": "पाठवत आहे..."
    },
    "symptom": {
      "title": "एआय लक्षणे तपासक",
      "subtitle": "तुम्हाला कसे वाटत आहे ते आम्हाला सांगा. आम्ही तुम्हाला पुढे काय करायचे याचे मार्गदर्शन करू.",
      "select_symptoms": "तुमची लक्षणे निवडा:",
      "check_now": "आता तपासा",
      "fever": "ताप",
      "cough": "खोकला",
      "chest_pain": "छातीत दुखणे",
      "breathing": "श्वास घेण्यास त्रास",
      "bleeding": "रक्तस्त्राव",
      "headache": "डोकेदुखी",
      "vomiting": "उलट्या",
      "weakness": "अशक्तपणा",
      "analyzing": "विश्लेषण करत आहे...",
      "go_hospital": "तात्काळ रुग्णालयात जा",
      "see_doctor": "आजच डॉक्टरांना भेटा",
      "mild": "सौम्य — घरी विश्रांती घ्या"
    }
  },
  "ta": {
    "dashboard": "நோயாளி டாஷ்போர்டு",
    "welcome_back": "வரவேற்கிறோம். எப்படி உதவலாம்?",
    "network_connected": "நெட்வொர்க் இணைக்கப்பட்டது",
    "swasthai": "SwasthAI",
    "national_impact": "தேசிய சுகாதார தாக்கம்",
    "tagline": "AI, ஆஃப்லைன் சினெர்ஜி மூலம் கிராமங்களை உலகத்தரம் வாய்ந்த மருத்துவ வசதிகளுடன் இணைக்கிறோம்.",
    "portal_access": "போர்டல்",
    "join_network": "இணையுங்கள்",
    "citizens_covered": "மக்கள் காப்பீடு",
    "network_uptime": "தொடரமைப்பு நேரம்",
    "villages_reached": "கிராமங்கள் அடைந்தன",
    "everything_you_need": "நல்ல ஆரோக்கியத்திற்கு",
    "for_good_health": "அனைத்தும்",
    "get_started_now": "இப்போதே தொடங்குங்கள்",
    "ready_to_transform": "கிராமப்புற சுகாதாரத்தை மாற்ற தயாரா?",
    "join_thousands": "சுகாதார கட்டமைப்பை எதிர்காலத்திற்கென அமைப்போருடன் இணையுங்கள்.",
    "footer_text": "© 2026 SwasthAI ஹெல்த்கேர் பிளாட்ஃபார்ம். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. IEEE சான்றளிக்கப்பட்டது.",
    "services": {
      "maternal": "தாய்மை நலம்",
      "maternal_desc": "சுகாதார ஆலோசனைகளை பாதுகாப்பாக பெறவும்.",
      "access_portal": "திறக்க",
      "symptoms": "ஸ்மார்ட் கண்டறிதல்",
      "symptoms_desc": "AI முதற்கட்ட பரிசோதனை",
      "how_feeling": "உங்களுக்கு என்ன பிரச்னை?",
      "check_symptoms": "பரிசோதிக்கவும்",
      "analyzing": "பகுப்பாய்வு...",
      "emergency": "அவசர சேவை",
      "immediate_assist": "விரைவான உதவி",
      "ambulance_desc": "ஆம்புலன்ஸ் அல்லது ஆஷா பணியாளரை உடனடியாக அழைக்கவும்.",
      "request_ambulance": "ஆம்புலன்ஸ் அழை",
      "dispatching": "அனுப்புகிறது...",
      "teleclinic": "காணொளி மருத்துவம்",
      "tele_desc": "நிபுணர் மருத்துவர்களுடன் நேரடி வீடியோ ஆலோசனை.",
      "academy": "சுகாதார விழிப்புணர்வு",
      "academy_desc": "நோய் தடுப்பு குறிப்புகள்.",
      "voice": "குரல் உதவியாளர்",
      "voice_desc": "தட்டச்சு செய்ய தேவையில்லை. பேசுவதன் மூலம் சேவைகளைப் பெறவும்.",
      "diagnostic": "கண்டறிதல் AI"
    },
    "nav": {
      "home": "முகப்பு",
      "check_symptoms": "பரிசோதிக்க",
      "skin_care": "சரும பராமரிப்பு",
      "ambulance": "ஆம்புலன்ஸ்",
      "menstrual_health": "தாய்மை நலம்",
      "offline_mode": "ஆஃப்லைன் பயன்முறை",
      "offline_desc": "அறிகுறி சோதனையாளர் வேலை செய்கிறார். குரல் மற்றும் AI க்கு இணையம் தேவை."
    },
    "roles": {
      "villager": "குடிமகன்",
      "ngo": "ஆஷா",
      "admin": "நிர்வாகி"
    },
    "login": "உள்நுழை",
    "register": "பதிவு",
    "logout": "வெளியேறு",
    "loginPage": {
      "left_title_1": "ஒவ்வொரு குடிமகனையும் இணைக்கிறோம்",
      "left_title_span": "தரமான மருத்துவத்துடன்.",
      "left_desc": "உங்கள் மருத்துவப் பதிவுகளை பாதுகாப்பாக அணுகவும், மருத்துவர்களை ஆலோசிக்கவும்.",
      "secure_private": "பாதுகாப்பானது மற்றும் தனிப்பட்டது",
      "secure_desc": "அனைத்து சுகாதார தரவுகளும் பாதுகாப்பான குறியாக்க முறைமைகளுடன் பராமரிக்கப்படுகின்றன.",
      "sign_in_desc": "உள்நுழையவும்.",
      "select_account": "கணக்கு வகையைத் தேர்ந்தெடுக்கவும்",
      "demo_patient": "மாதிரி நோயாளி",
      "demo_provider": "மாதிரி வழங்குநர்",
      "with_password": "கடவுச்சொல்லுடன்",
      "with_otp": "OTP உடன்",
      "phone_or_email": "தொலைபேசி எண் அல்லது மின்னஞ்சல்",
      "password": "கடவுச்சொல்",
      "enter_otp": "OTP ஐ உள்ளிடவும்",
      "placeholder_identifier": "எ.கா. 9876543210",
      "forgot_password": "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
      "placeholder_password": "••••••••",
      "placeholder_otp": "எ.கா. 123456",
      "get_otp": "OTP ஐப் பெறுக",
      "secure_sign_in": "பாதுகாப்பாக உள்நுழையவும்",
      "authenticating": "உள்நுழைகிறது...",
      "no_account": "கணக்கு இல்லையா?",
      "villager_sub": "நோயாளி",
      "ngo_sub": "சுகாதாரப் பணியாளர்",
      "admin_sub": "மேலாண்மை"
    },
    "registerPage": {
      "left_title_1": "எங்கள் நம்பகமான சுகாதார",
      "left_title_span": "பின்னலில் இணையுங்கள்.",
      "left_desc": "பரிசோதனைக்கு முன்பதிவு செய்ய கணக்கை உருவாக்கவும்.",
      "national_protocol": "தேசிய சுகாதார நெறிமுறை",
      "national_desc": "தரவுப் பாதுகாப்பு நெறிமுறைகள்.",
      "set_up_account": "உங்கள் கணக்கை அமைக்கவும்.",
      "account_created": "கணக்கு உருவாக்கப்பட்டது! உள்நுழைவதற்கு செல்கிறது...",
      "step1_role": "1. நான் பதிவு செய்கிறேன்...",
      "step2_personal": "2. தனிப்பட்ட தகவல்",
      "full_name": "முழு பெயர்",
      "choose_username": "பெயரைத் தேர்வுசெய்க",
      "step3_contact": "3. தொடர்பு விவரங்கள்",
      "phone_number": "தொலைபேசி எண்",
      "email_address": "மின்னஞ்சல்",
      "step4_security": "4. பாதுகாப்பு",
      "create_password": "கடவுச்சொல்லை உருவாக்கு",
      "step5_location": "5. இருப்பிட அடையாளம்",
      "village_id": "கிராம ஐடி (எ.கா., v101)",
      "securing_records": "பாதுகாக்கப்படுகிறது...",
      "account_verified": "சரிபார்க்கப்பட்டது",
      "already_have_account": "ஏற்கனவே கணக்கு உள்ளதா?",
      "sign_in_here": "இங்கே உள்நுழையவும்",
      "gen_demo_patient": "மாதிரி நோயாளி",
      "gen_demo_provider": "மாதிரி வழங்குநர்"
    },
    "diseaseChecker": {
      "ai_axis": "செயற்கை நுண்ணறிவு அச்சு V-02",
      "title": "நோய்",
      "title_span": "சோதனை.",
      "sys_load": "அமைப்பு சுமை: சீரானது",
      "node_loc": "முனை: வாரணாசி மையம்",
      "choose_symptoms": "அறிகுறிகளைத் தேர்ந்தெடுக்கவும்",
      "critical": "கடுமையான நெருக்கடி",
      "common": "பொதுவான",
      "describe_voice": "அல்லது உங்கள் உள்ளூர் மொழியில் உடல் நிலையை விவரிக்கவும்...",
      "init_scan": "ஸ்கேன் நெறிமுறையைத் தொடங்கு",
      "diag_await": "கண்டறியும் தரவு காத்திருக்கிறது",
      "init_axis": "கணக்கீடு செய்ய இடது அச்சைத் தொடங்கவும்",
      "processing_img": "புகைப்படம் மூலம் நோய் கண்டறியப்படும்",
      "local_link": "உள்ளூர் இணைப்பு",
      "varanasi_node": "வாரணாசி முனை V-01",
      "global_status": "உலகளாவிய நிலை",
      "online_sync": "ஆன்லைன் மற்றும் இணைக்கப்பட்டுள்ளது",
      "download_report": "பராமரிப்பு அறிக்கையை V-01 பதிவிறக்க (PDF)",
      "fever": "அதிக காய்ச்சல்",
      "cough": "தொடர்ச்சியான இருமல்",
      "chest_pain": "கடுமையான நெஞ்சு வலி",
      "breathing": "சுவாசிப்பதில் சிரமம்",
      "bleeding": "அதிக இரத்தப்போக்கு",
      "headache": "கடுமையான தலைவலி",
      "vomiting": "வாந்தி",
      "weakness": "அதிகப்படியான சோர்வு",
      "dizziness": "மயக்கம்",
      "vision_loss": "திடீர் பார்வை இழப்பு",
      "paralysis": "ஒரு பக்கத்தில் திடீர் பலவீனம்",
      "take_photo": "படம் எடுக்க",
      "take_photo_hi": "(கேமரா மூலம்)",
      "upload_photo": "படத்தைப் பதிவேற்றவும்",
      "upload_photo_hi": "(கேலரியில் இருந்து)",
      "drag_drop": "அல்லது இங்கே படத்தை இழுத்து விடவும்",
      "privacy_main": "உங்கள் படம் தனிப்பட்டது - இந்த சாதனத்தில் மட்டுமே பகுப்பாய்வு செய்யப்படும்",
      "privacy_sub": "உங்கள் படம் யாருக்கும் அனுப்பப்படாது."
    },
    "villagerDashboard": {
      "offline_active": "ஆஃப்லைன் நெறிமுறை செயலில் உள்ளது",
      "decentralized_health": "பரவலாக்கப்பட்ட சுகாதாரம். சரிபார்க்கப்பட்ட அடையாளம்.",
      "use_without_internet": "இணையம் இல்லாமல் பயன்பாடு",
      "go_online": "இணைய தொடர்பு கொள்",
      "skin_scanner": "சருமம் AI ஸ்கேனர்",
      "skin_scanner_desc": "சருமத் தொற்றுகளைப் பரிசோதிக்க படங்களைப் பதிவேற்றவும்.",
      "health_identity": "சுகாதார அடையாளம்",
      "health_identity_desc": "உங்கள் மருத்துவ வரலாற்றை நிர்வகிக்கவும்.",
      "voice_assistant": "குரல் உதவியாளர்",
      "voice_assistant_desc": "உங்கள் மொழியிலேயே பேசவும், டைப் செய்ய தேவையில்லை!"
    },
    "footer": {
      "empowering": "ஊரக பாரதத்தை மேம்படுத்துதல்",
      "description": "கிராமப்புற இந்தியாவில் உள்ள முக்கியமான சுகாதார இடைவெளியைக் குறைக்கிறது. ஒவ்வொரு கிராமத்திற்கும் உடனடி நோயறிதல் மற்றும் அவசர ஆதரவை வழங்க SwasthAI Guardian AI மற்றும் உள்ளூர் சுகாதார நெட்வொர்க்குகளை மேம்படுத்துகிறது.",
      "quick_access": "விரைவு அணுகல்",
      "connect": "தொடர்பு கொள்க",
      "regional_hub": "பிராந்திய மையம்",
      "address": "வாரணாசி, உத்தரபிரதேசம், இந்தியா",
      "support_line": "ஆதரவு வரி",
      "emergency_helplines": "அவசர ஹெல்ப்லைன்கள்",
      "national_health_axis": "தேசிய சுகாதார மையம்",
      "asha_alert": "ஆஷா பணியாளர் விரைவான எச்சரிக்கை",
      "request_assist": "உள்ளூர் உதவியைக் கோருங்கள்",
      "secured_by": "SwasthAI நெறிமுறைகளால் பாதுகாக்கப்படுகிறது",
      "copyright": "© 2026 SwasthAI Guardian. AI கண்டுபிடிப்பு மூலம் கிராமப்புற சுகாதாரங்களை நவீனமயமாக்குவதற்கான ஒரு பணி.",
      "privacy": "தனியுரிமை கொள்கை",
      "ethics": "டிஜிட்டல் நெறிமுறைகள்"
    },
    "intro": {
      "welcome_title": "SwasthAI Guardian-க்கு வரவேற்கிறோம்",
      "welcome_sub": "ஊரக சுகாதாரத்தின் எதிர்காலம் இங்கே உள்ளது. ஆஃப்லைன் மற்றும் AI வசதியுடன்.",
      "strategic_title": "மூலோபాయ சுகாதார மேற்பார்வை",
      "service_1_t": "AI கண்டறிதல்",
      "service_2_t": "அவசரக்கால பதில்",
      "service_3_t": "தாய்மை மற்றும் மாதவிடாய் பராமரிப்பு",
      "service_4_t": "டெலி-ஹెல்த் கனెக்ட்",
      "protocol_awareness": "அடுத்து: விழிப்புணர்வு நெறிமுறை",
      "select_title": "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
      "select_sub": "சிறந்த அனுபவத்திற்கு உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.",
      "establish_sync": "இணைப்பை ஏற்படுத்து"
    },
    "dashboardExt": {
      "maternal_pulse": "தாய்மை நலம்",
      "secure_axis": "பாதுகாப்பானது",
      "terminal_access": "திறக்க",
      "my_profile": "என் சுயவிவரம்",
      "profile_desc": "உங்கள் சுகாதார ஐடியைப் பார்க்கவும், பெயரைப் புதுப்பிக்கவும்.",
      "open": "திறக்க",
      "skin_ai": "சரும AI ஸ்கேனர்",
      "skin_ai_desc": "சருமத் தொற்றுகளை எளிதாகப் பரிசோதிக்கவும்.",
      "symptom_checker": "அறிகுறி பரிசோதகர்",
      "symptom_checker_desc": "உங்கள் அறிகுறிகளைப் பரிசோதித்து ஆலோசனை பெறவும்.",
      "greeting": "வணக்கம், நாங்கள் உங்களுக்கு எவ்வாறு உதவ முடியும்?"
    },
    "menstrual": {
      "title": "பெண்கள் நலம்",
      "safe_private": "பாதுகாப்பானது",
      "subtitle": "AI சுகாதார வழிகாட்டுதல், அறிகுறி பரிசோதனை மற்றும் இலவச பேட் - முற்றிலும் தனிப்பட்டது.",
      "emergency_help": "அவசர உதவி",
      "ai_assistant": "AI உதவியாளர்",
      "symptom_check": "அறிகுறி பரிசோதனை",
      "request_pads": "பேட் கோரிக்கை",
      "health_tips": "சுகாதார குறிப்புகள்",
      "request_pads_title": "சானிட்டரி பேட் கோரிக்கை",
      "request_pads_desc": "உங்கள் ஆஷா பணியாளர் உங்களுக்கு பேட்களை வழங்குவார். இந்த கோரிக்கை முற்றிலும் ரகசியமானது.",
      "private_note": "100% தனிப்பட்டது — உங்கள் ஆஷா பணியாளர் மட்டுமே இந்த கோரிக்கையை காண முடியும்.",
      "your_village": "உங்கள் கிராமம் / பகுதி",
      "village_placeholder": "எ.கா. ராம்பூர், செக்டார் 4",
      "request_btn": "ஆஷா பணியாளரிடம் பேட் கோரிக்கை",
      "request_sent": "கோரிக்கை அனுப்பப்பட்டது!",
      "request_sent_desc": "உங்கள் ஆஷா பணியாளருக்கு தெரிவிக்கப்பட்டுள்ளது, அவர் விரைவில் உங்களை தொடர்புகொள்வார்.",
      "send_another": "மற்றொரு கோரிக்கையை அனுப்பவும்",
      "symptom_title": "அறிகுறி பரிசோதனை",
      "symptom_desc": "நீங்கள் உணரும் எந்த அறிகுறிகளையும் தேர்ந்தெடுக்கவும். இது ஒரு நோய் கண்டறிதல் அல்ல - எப்போதும் மருத்துவரை அணுகவும்.",
      "check_btn": "என் அறிகுறிகளைப் பரிசோதிக்கவும்",
      "tips_title": "சுகாதார குறிப்புகள்",
      "tips_desc": "உங்கள் மாதவிடாய் காலத்தில் உங்கள் ஆரோக்கியத்திற்கான எளிய ஆலோசனைகள்.",
      "ask_anything": "உங்கள் ஆரோக்கியம் குறித்து எதையும் கேளுங்கள்...",
      "emergency_title": "அவசர உதவி",
      "emergency_desc": "உங்கள் ஆஷா பணியாளரை உடனடியாக எச்சரிக்க கீழே உள்ள பட்டனை அழுத்தவும். அவர் உங்களை அழைத்து உதவ வருவார்.",
      "alert_asha": "என் ஆஷா பணியாளரை இப்போது எச்சரிக்கவும்",
      "call_ambulance": "108-இலவச ஆம்புலன்ஸை அழைக்கவும்"
    },
    "ambulance": {
      "title": "அவசர மீட்பு",
      "subtitle": "ஆம்புலன்ஸ் அல்லது சுகாதார பணியாளர் தேவையா? கீழே கிளிக் செய்யவும். உங்கள் இருப்பிடம் தானாகவே பகிரப்படும்.",
      "request_team": "அவசர குழுவை அழைக்கவும்",
      "non_critical": "சாதாரண மருத்துவ போக்குவரத்து",
      "rescue_dispatched": "மீட்பு குழு அனுப்பப்பட்டது",
      "call_driver": "ஓட்டுநரை அழைக்கவும்",
      "dispatching": "அனுப்புகிறது...",
      "patient_name": "நோயாளியின் பெயர்",
      "contact_number": "தொடர்பு எண்",
      "emergency_type": "அவசர வகை",
      "location": "உங்கள் இருப்பிடம்",
      "accident": "சாலை விபத்து",
      "accident_hi": "",
      "pregnancy": "கர்ப்பக்கால அவசரம்",
      "pregnancy_hi": "",
      "heart": "மாரடைப்பு",
      "heart_hi": "",
      "respiratory": "சுவாசப் பிரச்சனை",
      "respiratory_hi": "",
      "trauma": "கடுமையான காயம்",
      "trauma_hi": "",
      "general": "பொதுவான அவசரம்",
      "general_hi": "",
      "no_time": "படிவத்தை நிரப்ப நேரமில்லையா?",
      "sos_desc": "இந்த பொத்தானை அழுத்தவும். உங்களைக் கண்டறிய ஜிபிஎஸ் மூலம் ஆம்புலன்ஸ் உடனடியாக அனுப்பப்படும்.",
      "sos_btn": "SOS — உதவிக்கு அழைக்கவும்"
    },
    "symptom": {
      "title": "AI அறிகுறி பரிசோதகர்",
      "subtitle": "நீங்கள் எப்படி உணருகிறீர்கள் என்பதை எங்களிடம் கூறுங்கள். அடுத்து என்ன செய்ய வேண்டும் என்பதை நாங்கள் உங்களுக்கு வழிகாட்டுவோம்.",
      "select_symptoms": "உங்கள் அறிகுறிகளைத் தேர்ந்தெடுக்கவும்:",
      "check_now": "இப்போது சரிபார்க்கவும்",
      "fever": "காய்ச்சல்",
      "cough": "இருமல்",
      "chest_pain": "நெஞ்சு வலி",
      "breathing": "சுவாசிப்பதில் சிரமம்",
      "bleeding": "இரத்தப்போக்கு",
      "headache": "தலைவலி",
      "vomiting": "வாந்தி",
      "weakness": "சோர்வு",
      "analyzing": "பகுப்பாய்வு...",
      "go_hospital": "உடனடியாக மருத்துவமனைக்குச் செல்லவும்",
      "see_doctor": "இன்றே மருத்துவரைப் பார்க்கவும்",
      "mild": "லேசானது — வீட்டில் ஓய்வெடுக்கவும்"
    }
  },
  "te": {
    "dashboard": "పేషెంట్ డాష్‌బోర్డ్",
    "welcome_back": "స్వాగతం. మేం మీకు ఎలా సాయపడగలం?",
    "network_connected": "నెట్‌వర్క్ కనెక్ట్ అయింది",
    "swasthai": "SwasthAI",
    "national_impact": "జాతీయ ఆరోగ్య ప్రభావం",
    "tagline": "మేము మారుమూల గ్రామాలను ప్రపంచ స్థాయి వైద్య సదుపాయాలతో అనుసంధానిస్తాము.",
    "portal_access": "పోర్టల్ తెరవండి",
    "join_network": "నెట్‌వర్క్‌లో చేరండి",
    "citizens_covered": "కవర్ చేయబడిన పౌరులు",
    "network_uptime": "నెట్‌వర్క్ అప్‌టైమ్",
    "villages_reached": "గ్రామాలు చేరుకున్నాయి",
    "everything_you_need": "కావలసినదంతా",
    "for_good_health": "మంచి ఆరోగ్యం కోసం",
    "get_started_now": "ఇప్పుడే ప్రారంభించండి",
    "ready_to_transform": "మార్పు కోసం సిద్ధంగా ఉన్నారా?",
    "join_thousands": "ఆరోగ్య మౌలిక సదుపాయాలను నిర్మిస్తున్న వేలాది మందితో చేరండి.",
    "footer_text": "© 2026 స్వస్థ్ఏఐ హెల్త్‌కేర్ ప్లాట్‌ఫారమ్. సర్వ హక్కులు ప్రత్యేకించబడ్డాయి. IEEE ధృవీకరించబడింది.",
    "services": {
      "maternal": "మాతృ ఆరోగ్యం",
      "maternal_desc": "గర్భిణీ స్త్రీలకు సురక్షితమైన వైద్య సలహాలు.",
      "access_portal": "పోర్టల్ తెరవండి",
      "symptoms": "స్మార్ట్ డయాగ్నోస్టిక్స్",
      "symptoms_desc": "AI ప్రాథమిక పరీక్ష",
      "how_feeling": "మీకు ఎలా ఉంది?",
      "check_symptoms": "రోగనిర్ధారణ ప్రారంభించండి",
      "analyzing": "విశ్లేషిస్తోంది...",
      "emergency": "అత్యవసర కేంద్రం",
      "immediate_assist": "తక్షణ సహాయం",
      "ambulance_desc": "అంబులెన్స్ లేదా ఆశా వర్కర్‌ను తక్షణమే పంపండి.",
      "request_ambulance": "అంబులెన్స్ పిలవండి",
      "dispatching": "పంపుతోంది...",
      "teleclinic": "టెలిమెడిసిన్",
      "tele_desc": "డాక్టర్లతో ప్రత్యక్ష వీడియో కన్సల్టేషన్.",
      "academy": "ఆరోగ్య అకాడమీ",
      "academy_desc": "వ్యాధుల నివారణ సమాచారం.",
      "voice": "వాయిస్ అసిస్టెంట్",
      "voice_desc": "టైప్ చేయాల్సిన పనిలేదు, మాట్లాడటం ద్వారా సేవలను పొందండి.",
      "diagnostic": "డయాగ్నోస్టిక్ AI"
    },
    "nav": {
      "home": "హోమ్",
      "check_symptoms": "రోగనిర్ధారణ",
      "skin_care": "చర్మానికి రక్షణ",
      "ambulance": "అంబులెన్స్",
      "menstrual_health": "మాతృ ఆరోగ్యం",
      "offline_mode": "ఆఫ్‌లైన్ మోడ్",
      "offline_desc": "లక్షణ తనిఖీ పని చేస్తుంది. వాయిస్ మరియు AI కోసం ఇంటర్నెట్ అవసరం."
    },
    "roles": {
      "villager": "పౌరుడు",
      "ngo": "ఆశా",
      "admin": "నిర్వాహకుడు"
    },
    "login": "లాగిన్",
    "register": "నమోదు",
    "logout": "లాగ్అవుట్",
    "loginPage": {
      "left_title_1": "ప్రతి పౌరుడికి అనుసంధానం",
      "left_title_span": "నాణ్యమైన వైద్యాన్ని.",
      "left_desc": "మీ వైద్య రికార్డులను సురక్షితంగా యాక్సెస్ చేయండి.",
      "secure_private": "సురక్షితమైన & ప్రైవేట్",
      "secure_desc": "అన్ని ఆరోగ్య డేటా ఎన్క్రిప్షన్ ప్రోటోకాల్స్ కింద రక్షించబడింది.",
      "sign_in_desc": "దయచేసి సైన్ ఇన్ చేయండి.",
      "select_account": "ఖాతా రకాన్ని ఎంచుకోండి",
      "demo_patient": "డెమో పేషెంట్",
      "demo_provider": "డెమో ప్రొవైడర్",
      "with_password": "పాస్‌వర్డ్‌తో",
      "with_otp": "OTP తో",
      "phone_or_email": "ఫోన్ నంబర్ లేదా ఇమెయిల్",
      "password": "పాస్‌వర్డ్",
      "enter_otp": "OTP నమోదు చేయండి",
      "placeholder_identifier": "ఉదా. 9876543210",
      "forgot_password": "పాస్‌వర్డ్ మర్చిపోయారా?",
      "placeholder_password": "••••••••",
      "placeholder_otp": "ఉదా. 123456",
      "get_otp": "OTP పొందండి",
      "secure_sign_in": "రక్షిత సైన్ ఇన్",
      "authenticating": "ప్రామాణీకరిస్తోంది...",
      "no_account": "ఖాతా లేదా?",
      "villager_sub": "రోగి / పౌరుడు",
      "ngo_sub": "ఆరోగ్య కార్యకర్త",
      "admin_sub": "నిర్వహణ"
    },
    "registerPage": {
      "left_title_1": "మా విశ్వసనీయ ఆరోగ్య",
      "left_title_span": "నెట్‌వర్క్‌లో చేరండి.",
      "left_desc": "సురక్షితంగా రికార్డులను నిర్వహించడానికి ఖాతా సృష్టించండి.",
      "national_protocol": "జాతీయ ఆరోగ్య ప్రోటోకాల్",
      "national_desc": "అన్ని ప్రొఫైళ్లు సురక్షితంగా ఉంటాయి.",
      "set_up_account": "మీ ఖాతాను సెట్ చేయండి.",
      "account_created": "ఖాతా సృష్టించబడింది! లాగిన్‌కి వెళ్తోంది...",
      "step1_role": "1. నేను నమోదు చేస్తున్నాను...",
      "step2_personal": "2. వ్యక్తిగత సమాచారం",
      "full_name": "పూర్తి పేరు",
      "choose_username": "వినియోగదారు పేరు ఎంచుకోండి",
      "step3_contact": "3. సంప్రదింపు వివరాలు",
      "phone_number": "ఫోన్ నంబర్",
      "email_address": "ఈమెయిల్ అడ్రస్",
      "step4_security": "4. భద్రత",
      "create_password": "పాస్‌వర్డ్ సృష్టించండి",
      "step5_location": "5. స్థాన గుర్తింపు",
      "village_id": "గ్రామం ID (ఉదా., v101)",
      "securing_records": "భద్రపరుస్తోంది...",
      "account_verified": "ఖాతా ధృవీకరించబడింది",
      "already_have_account": "ఇంతకుముందే ఖాతా ఉందా?",
      "sign_in_here": "ఇక్కడ సైన్ ఇన్ చేయండి",
      "gen_demo_patient": "డెమో పేషెంట్ సృష్టించండి",
      "gen_demo_provider": "డెమో ప్రొవైడర్ సృష్టించండి"
    },
    "diseaseChecker": {
      "ai_axis": "AI డయాగ్నోస్టిక్ యాక్సిస్ V-02",
      "title": "రోగ",
      "title_span": "తనిఖీ.",
      "sys_load": "సిస్టమ్ లోడ్: స్థిరంగా",
      "node_loc": "నోడ్: వారణాసి సెంట్రల్",
      "choose_symptoms": "లక్షణాలను ఎంచుకోండి",
      "critical": "క్లిష్టమైన",
      "common": "సాధారణ",
      "describe_voice": "లేదా మీ ఆరోగ్య పరిస్థితిని స్థానిక భాషలో వివరించండి...",
      "init_scan": "స్కాన్ ప్రోటోకాల్‌ను ప్రారంభించండి",
      "diag_await": "రోగ నిర్ధారణ డేటా కోసం వేచి ఉంది",
      "init_axis": "లెక్కింపు కోసం ఎడమ అక్షాన్ని ప్రారంభించండి",
      "processing_img": "ఫోటో ద్వారా వ్యాధి గుర్తించబడుతుంది",
      "local_link": "స్థానిక లింక్",
      "varanasi_node": "వారణాసి నోడ్ V-01",
      "global_status": "గ్లోబల్ స్థితి",
      "online_sync": "ఆన్‌లైన్ & సింక్ అవుతోంది",
      "download_report": "కేర్ రిపోర్ట్ V-01 డౌన్‌లోడ్ (PDF)",
      "fever": "అధిక జ్వరం",
      "cough": "నిరంతర దగ్గు",
      "chest_pain": "తీవ్రమైన ఛాతీ నొప్పి",
      "breathing": "శ్వాస తీసుకోవడంలో ఇబ్బంది",
      "bleeding": "అధిక రక్తస్రావం",
      "headache": "తీవ్రమైన తలనొప్పి",
      "vomiting": "వాంతులు",
      "weakness": "అత్యంత బలహీనత",
      "dizziness": "తలతిరగడం",
      "vision_loss": "అకస్మాత్తుగా చూపు కోల్పోవడం",
      "paralysis": "ఒక వైపు అకస్మాత్తుగా బలహీనత"
    },
    "villagerDashboard": {
      "offline_active": "ఆఫ్‌లైన్ ప్రోటోకాల్ యాక్టివ్",
      "decentralized_health": "వికేంద్రీకృత ఆరోగ్య సంరక్షణ. సురక్షిత గుర్తింపు.",
      "use_without_internet": "ఇంటర్నెట్ లేకుండా ఉపయోగించండి",
      "go_online": "ఆన్‌లైన్‌కు వెళ్లండి",
      "skin_scanner": "స్కిన్ AI స్కానర్",
      "skin_scanner_desc": "చర్మ అంటువ్యాధులను తనిఖీ చేయడానికి ఫోటోలను అప్‌లోడ్ చేయండి.",
      "health_identity": "ఆరోగ్య గుర్తింపు",
      "health_identity_desc": "మీ వైద్య చరిత్రను నిర్వహించండి.",
      "voice_assistant": "వాయిస్ అసిస్టెంట్",
      "voice_assistant_desc": "మాట్లాడితే చాలు, ఏదీ టైప్ చేయనవసరం లేదు!"
    },
    "footer": {
      "empowering": "గ్రామీణ భారత్‌కు సాధికారత",
      "description": "గ్రామీణ భారతదేశంలో క్లిష్టమైన ఆరోగ్య సంరక్షణ అంతరాన్ని తగ్గిస్తోంది. ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ (AI) మరియు స్థానిక ఆరోగ్య నెట్‌వర్క్‌లను ఉపయోగించి ప్రతి విలేజీకి తక్షణ విశ్లేషణలు మరియు అత్యవసర సపోర్టును అందించడానికి SwasthAI Guardian కృషి చేస్తోంది.",
      "quick_access": "క్విక్ యాక్సెస్",
      "connect": "కనెక్ట్",
      "regional_hub": "ప్రాంతీయ హబ్",
      "address": "వారణాసి, ఉత్తర ప్రదేశ్, ఇండియా",
      "support_line": "సపోర్ట్ లైన్",
      "emergency_helplines": "అత్యవసర హెల్ప్‌లైన్‌లు",
      "national_health_axis": "నేషనల్ హెల్త్ యాక్సిస్",
      "asha_alert": "ఆశా వర్కర్ క్విక్ అలర్ట్",
      "request_assist": "స్థానిక సహాయాన్ని అభ్యర్థించండి",
      "secured_by": "SwasthAI ప్రోటోకాల్స్ ద్వారా సురక్షితం",
      "copyright": "© 2026 SwasthAI Guardian. AI ఇన్నోవేషన్ ద్వారా గ్రామీణ ఆరోగ్య సంరక్షణను ఆధునికీకరించే మిషన్.",
      "privacy": "గోప్యతా విధానం",
      "ethics": "డిజిటల్ నైతికత"
    },
    "intro": {
      "welcome_title": "SwasthAI గార్డియన్‌కు స్వాగతం",
      "welcome_sub": "గ్రామీణ ఆరోగ్య సంరక్షణ భవిష్యత్తు ఇక్కడ ఉంది. ఆఫ్‌లైన్ మరియు AI సదుపాయంతో.",
      "strategic_title": "వ్యూహాత్మక ఆరోగ్య పర్యవేక్షణ",
      "service_1_t": "స్మార్ట్ AI డయాగ్నోస్టిక్స్",
      "service_1_d": "మా ఆఫ్‌లైన్ AI నోడ్లను ఉపయోగించి తక్షణ ఆరోగ్య అంచనాలను పొందండి.",
      "service_2_t": "అత్యవసర ప్రోటోకాల్",
      "service_2_d": "క్లిష్టమైన సంరక్షణ కోసం వన్-ట్యాప్ అంబులెన్స్ డిస్పాచ్ మరియు ఆశా కార్యకర్త హెచ్చరికలు.",
      "service_3_t": "మాతృత్వం & పీరియడ్ హబ్",
      "service_3_d": "మహిళల ఆరోగ్యం కోసం సురక్షితమైన, ప్రైవేట్ ట్రాకింగ్ మరియు క్లినికల్ మార్గదర్శకత్వం.",
      "service_4_t": "టెలి-హెల్త్ బ్రిడ్జ్",
      "service_4_d": "పట్టణ నిపుణులతో నేరుగా హై-కంప్రెషన్ వీడియో/ఆడియో సంప్రదింపులు.",
      "service_5_t": "వికేంద్రీకృత హెల్త్ ఐడిలు",
      "service_5_d": "మీ కుటుంబం మొత్తానికి డిజిటల్ మెడికల్ రికార్డులను ఒకే సురక్షిత ప్రదేశంలో నిర్వహించండి.",
      "service_6_t": "స్కిన్ AI స్కానర్",
      "service_6_d": "చర్మ అంటువ్యాధులు మరియు పరిస్థితుల కోసం తక్షణ క్లినికల్-గ్రేడ్ విశ్లేషణ.",
      "protocol_awareness": "తదుపరి: ప్రోటోకాల్ అవగాహన",
      "select_title": "మీ భాషను ఎంచుకోండి",
      "select_sub": "మెరుగైన అనుభవం కోసం దయచేసి మీ ప్రాధాన్యత భాషను ఎంచుకోండి.",
      "establish_sync": "సింక్ స్థాపించండి"
    },
    "dashboardExt": {
      "maternal_pulse": "మాతృ ఆరోగ్యం",
      "secure_axis": "సురక్షితమైనది",
      "terminal_access": "తెరవండి",
      "my_profile": "నా ప్రొఫైల్",
      "profile_desc": "మీ హెల్త్ ఐడీని చూడండి, పేరును అప్‌డేట్ చేయండి.",
      "open": "తెరవండి",
      "skin_ai": "స్కిన్ AI స్కానర్",
      "skin_ai_desc": "చర్మ ఇన్ఫెక్షన్లను సులభంగా తనిఖీ చేయండి.",
      "symptom_checker": "సింప్టమ్ చెకర్",
      "symptom_checker_desc": "మీ లక్షణాలను తనిఖీ చేసి సలహా పొందండి.",
      "greeting": "నమస్కారం, మేము మీకు ఎలా సహాయపడగలము?"
    },
    "menstrual": {
      "title": "మహిళల ఆరోగ్యం",
      "safe_private": "సురక్షితమైనది",
      "subtitle": "AI ఆరోగ్య మార్గదర్శకత్వం, లక్షణాల తనిఖీ మరియు ఉచిత ప్యాడ్ - పూర్తిగా ప్రైవేట్.",
      "emergency_help": "అత్యవసర సహాయం",
      "ai_assistant": "AI అసిస్టెంట్",
      "symptom_check": "లక్షణాల తనిఖీ",
      "request_pads": "ప్యాడ్స్ అభ్యర్థన",
      "health_tips": "ఆరోగ్య చిట్కాలు",
      "request_pads_title": "శానిటరీ ప్యాడ్స్ అభ్యర్థించండి",
      "request_pads_desc": "మీ ఆశా వర్కర్ మీకు ప్యాడ్స్ అందిస్తారు. ఈ అభ్యర్థన పూర్తిగా గోప్యమైనది.",
      "private_note": "100% ప్రైవేట్ — మీ ఆశా వర్కర్ మాత్రమే ఈ అభ్యర్థనను చూడగలరు.",
      "your_village": "మీ గ్రామం / ప్రాంతం",
      "village_placeholder": "ఉదా. రాంపూర్, సెక్టార్ 4",
      "request_btn": "ఆశా వర్కర్ నుండి ప్యాడ్స్ అభ్యర్థించండి",
      "request_sent": "అభ్యర్థన పంపబడింది!",
      "request_sent_desc": "మీ ఆశా వర్కర్‌కు తెలియజేయబడింది, వారు త్వరలో మిమ్మల్ని సంప్రదిస్తారు.",
      "send_another": "మరొక అభ్యర్థనను పంపండి",
      "symptom_title": "లక్షణాల తనిఖీ",
      "symptom_desc": "మీకు ఉన్న ఏవైనా లక్షణాలను ఎంచుకోండి. ఇది రోగ నిర్ధారణ కాదు - ఎల్లప్పుడూ వైద్యుడిని సంప్రదించండి.",
      "check_btn": "నా లక్షణాలను తనిఖీ చేయండి",
      "tips_title": "ఆరోగ్య చిట్కాలు",
      "tips_desc": "మీ పీరియడ్స్ సమయంలో మీ ఆరోగ్యానికి సులభమైన మరియు నిరూపితమైన సలహా.",
      "ask_anything": "మీ ఆరోగ్యం గురించి ఏదైనా అడగండి...",
      "emergency_title": "అత్యవసర సహాయం",
      "emergency_desc": "మీ ఆశా వర్కర్‌ను వెంటనే అప్రమత్తం చేయడానికి క్రింది బటన్‌ను నొక్కండి. వారు మీకు కాల్ చేసి సహాయం చేస్తారు.",
      "alert_asha": "నా ఆశా వర్కర్‌ను ఇప్పుడే అప్రమత్తం చేయండి",
      "call_ambulance": "108-ఉచిత అంబులెన్స్‌కు కాల్ చేయండి"
    },
    "ambulance": {
      "title": "అత్యవసర రెస్క్యూ",
      "subtitle": "అంబులెన్స్ లేదా ఆరోగ్య కార్యకర్త కావాలా? క్రింద క్లిక్ చేయండి. మీ స్థానం స్వయంచాలకంగా భాగస్వామ్యం చేయబడుతుంది.",
      "request_team": "ఎమర్జెన్సీ టీమ్‌ను అభ్యర్థించండి",
      "non_critical": "సాధారణ వైద్య రవాణా",
      "rescue_dispatched": "రెస్క్యూ డిస్పాచ్ చేయబడింది",
      "call_driver": "డ్రైవర్‌కు కాల్ చేయండి",
      "dispatching": "పంపుతోంది..."
    },
    "symptom": {
      "title": "AI సింప్టమ్ చెకర్",
      "subtitle": "మీకు ఎలా ఉందో మాకు చెప్పండి. తర్వాత ఏమి చేయాలో మేము మీకు మార్గనిర్దేశం చేస్తాము.",
      "select_symptoms": "మీ లక్షణాలను ఎంచుకోండి:",
      "check_now": "ఇప్పుడే తనిఖీ చేయండి",
      "fever": "జ్వరం",
      "cough": "దగ్గు",
      "chest_pain": "ఛాతీ నొప్పి",
      "breathing": "శ్వాస తీసుకోవడంలో ఇబ్బంది",
      "bleeding": "రక్తస్రావం",
      "headache": "తలనొప్పి",
      "vomiting": "వాంతులు",
      "weakness": "బలహీనత",
      "analyzing": "విశ్లేషిస్తోంది...",
      "go_hospital": "వెంటనే ఆసుపత్రికి వెళ్లండి",
      "see_doctor": "ఈరోజే వైద్యుడిని కలవండి",
      "mild": "తేలికపాటి — ఇంట్లో విశ్రాంతి తీసుకోండి"
    }
  },
  "bn": {
    "dashboard": "নাগরিক ড্যাশবোর্ড",
    "welcome_back": "স্বাগতম। আজ আমরা আপনাকে কীভাবে সাহায্য করতে পারি?",
    "network_connected": "নেটওয়ার্ক সংযুক্ত",
    "swasthai": "SwasthAI",
    "national_impact": "জাতীয় স্বাস্থ্য প্রভাব",
    "tagline": "আমরা এআই ডায়াগনস্টিকস, অফলাইন সমন্বয় এবং নিবেদিত স্বাস্থ্যসেবা কর্মীদের মাধ্যমে দূরবর্তী গ্রামগুলোকে বিশ্বমানের চিকিৎসা সুবিধার সাথে সংযুক্ত করি।",
    "portal_access": "পোর্টাল খুলুন",
    "join_network": "নেটওয়ার্কে যোগ দিন",
    "citizens_covered": "নাগরিক কভার করা হয়েছে",
    "network_uptime": "নেটওয়ার্ক আপটাইম",
    "villages_reached": "গ্রামে পৌঁছেছে",
    "everything_you_need": "ভালো স্বাস্থ্যের জন্য",
    "for_good_health": "সবকিছু",
    "get_started_now": "এখনই শুরু করুন",
    "ready_to_transform": "আপনি কি গ্রামীণ স্বাস্থ্যসেবা পরিবর্তন করতে প্রস্তুত?",
    "join_thousands": "হাজার হাজার আশা কর্মী, ডাক্তার এবং নাগরিকদের সাথে যোগ দিন যারা ব্যাপক স্বাস্থ্য পরিকাঠামোর ভবিষ্যৎ নির্মাণ করছেন।",
    "footer_text": "© ২০২৬ SwasthAI স্বাস্থ্যসেবা প্ল্যাটফর্ম। সর্বস্বত্ব সংরক্ষিত। IEEE প্রত্যয়িত।",
    "services": {
      "maternal": "মাতৃ কল্যাণ",
      "maternal_desc": "গোপনীয় ক্লিনিকাল নির্দেশনা, মাসিক ট্র্যাকিং এবং মাতৃ সহায়তা পান।",
      "access_portal": "পোর্টাল খুলুন",
      "symptoms": "স্মার্ট ডায়াগনস্টিকস",
      "symptoms_desc": "এআই চালিত প্রাথমিক ডায়াগনোসিস",
      "how_feeling": "আপনি কেমন অনুভব করছেন তা বর্ণনা করুন:",
      "check_symptoms": "লক্ষণ পরীক্ষা করুন",
      "analyzing": "বিশ্লেষণ করা হচ্ছে...",
      "emergency": "জরুরি কেন্দ্র",
      "immediate_assist": "তাত্ক্ষণিক সহায়তা",
      "ambulance_desc": "জরুরি অ্যাম্বুলেন্স বা আশা কর্মীর প্রয়োজন? জিপিএস অবস্থান শেয়ার করা হবে।",
      "request_ambulance": "অ্যাম্বুলেন্স ডাকুন",
      "dispatching": "পাঠানো হচ্ছে...",
      "teleclinic": "টেলি-মেডিসিন",
      "tele_desc": "শহরের ডাক্তারদের সাথে সরাসরি ভিডিও কনসালটেশন।",
      "academy": "স্বাস্থ্য সচেতনতা",
      "academy_desc": "রোগ প্রতিরোধ এবং পুষ্টির তথ্য।",
      "voice": "ভয়েস অ্যাসিস্ট্যান্ট",
      "voice_desc": "আপনার নিজস্ব ভাষায় কথা বলুন। টাইপ করার প্রয়োজন নেই।",
      "diagnostic": "এআই ডায়াগনস্টিক"
    },
    "nav": {
      "home": "হোম",
      "check_symptoms": "লক্ষণ পরীক্ষা",
      "skin_care": "ত্বকের যত্ন",
      "ambulance": "অ্যাম্বুলেন্স",
      "menstrual_health": "মাতৃ কল্যাণ",
      "profile": "প্রোফাইল"
    },
    "roles": {
      "villager": "নাগরিক",
      "ngo": "আশা",
      "admin": "প্রশাসক"
    },
    "login": "লগইন",
    "register": "নিবন্ধন",
    "logout": "লগআউট",
    "loginPage": {
      "left_title_1": "প্রতিটি নাগরিককে সংযুক্ত করা",
      "left_title_span": "মানসম্মত স্বাস্থ্যসেবার সাথে।",
      "left_desc": "নিরাপদভাবে আপনার মেডিকেল রেকর্ড অ্যাক্সেস করুন এবং লোকাল ভাষায় জরুরি সহায়তা পান।",
      "secure_private": "নিরাপদ ও ব্যক্তিগত",
      "secure_desc": "সমস্ত স্বাস্থ্য তথ্য শক্তিশালী এনক্রিপশন প্রোটোকলের অধীনে সুরক্ষিত।",
      "sign_in_desc": "আপনার ড্যাশবোর্ড অ্যাক্সেস করতে সাইন ইন করুন।",
      "select_account": "অ্যাকাউন্টের ধরন নির্বাচন করুন",
      "demo_patient": "ডেমো রোগী পূরণ করুন",
      "demo_provider": "ডেমো আশা কর্মী পূরণ করুন",
      "with_password": "পাসওয়ার্ড দিয়ে",
      "with_otp": "ওটিপি দিয়ে",
      "phone_or_email": "ফোন নম্বর বা ইমেল",
      "password": "পাসওয়ার্ড",
      "enter_otp": "ওটিপি লিখুন",
      "placeholder_identifier": "উদাঃ ৯৮৭৬৫৪৩২১০",
      "forgot_password": "পাসওয়ার্ড ভুলে গেছেন?",
      "placeholder_password": "••••••••",
      "placeholder_otp": "উদাঃ ১২৩৪৫৬",
      "get_otp": "ওটিপি পান",
      "secure_sign_in": "সাইন ইন করুন",
      "authenticating": "প্রমাণীকরণ করা হচ্ছে...",
      "no_account": "আপনার কি অ্যাকাউন্ট নেই?",
      "villager_sub": "রোগী / নাগরিক",
      "ngo_sub": "স্বাস্থ্যসেবা প্রদানকারী",
      "admin_sub": "ব্যবস্থাপনা"
    },
    "registerPage": {
      "left_title_1": "আমাদের বিশ্বস্ত স্বাস্থ্য",
      "left_title_span": "নেটওয়ার্কে যোগ দিন।",
      "left_desc": "নিরাপদভাবে অ্যাপয়েন্টমেন্ট বুক করতে এবং পরিবারের রেকর্ড ট্র্যাক করতে অ্যাকাউন্ট তৈরি করুন।",
      "national_protocol": "জাতীয় স্বাস্থ্য প্রোটোকল",
      "national_desc": "সমস্ত প্রোফাইল ডেটা সুরক্ষিত।",
      "set_up_account": "আপনার অ্যাকাউন্ট সেট আপ করুন।",
      "account_created": "অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে! লগইন এ নিয়ে যাওয়া হচ্ছে...",
      "step1_role": "১. আমি নিবন্ধন করছি...",
      "step2_personal": "২. ব্যক্তিগত তথ্য",
      "full_name": "পুরো নাম",
      "choose_username": "ব্যবহারকারীর নাম চয়ন করুন",
      "step3_contact": "৩. যোগাযোগের বিবরণ",
      "phone_number": "ফোন নম্বর",
      "email_address": "ইমেল ঠিকানা",
      "step4_security": "৪. নিরাপত্তা",
      "create_password": "একটি শক্তিশালী পাসওয়ার্ড তৈরি করুন",
      "step5_location": "৫. লোকাল আইডি",
      "village_id": "ভিলেজ আইডি (উদাঃ v101)",
      "securing_records": "রেকর্ড সুরক্ষিত করা হচ্ছে...",
      "account_verified": "অ্যাকাউন্ট যাচাই করা হয়েছে",
      "already_have_account": "আপনার কি ইতিমধ্যেই অ্যাকাউন্ট আছে?",
      "sign_in_here": "এখানে সাইন ইন করুন",
      "gen_demo_patient": "ডেমো রোগী তৈরি করুন",
      "gen_demo_provider": "ডেমো প্রদানকারী তৈরি করুন"
    },
    "diseaseChecker": {
      "ai_axis": "এআই ডায়াগনস্টিক এক্সিস V-02",
      "title": "রোগ",
      "title_span": "চেকার।",
      "sys_load": "সিস্টেম লোড: স্থিতিশীল",
      "node_loc": "নোড: বারাণসী সেন্ট্রাল",
      "choose_symptoms": "লক্ষণ নির্বাচন করুন",
      "critical": "গুরুতর",
      "common": "সাধারণ",
      "describe_voice": "অথবা স্থানীয় ভাষায় আপনার শারীরিক অবস্থা বর্ণনা করুন...",
      "init_scan": "স্ক্যান প্রোটোকল শুরু করুন",
      "diag_await": "ডায়াগনস্টিক ডেটার জন্য অপেক্ষা করা হচ্ছে",
      "init_axis": "গণনা করতে বাম এক্সিস শুরু করুন",
      "processing_img": "ফটো থেকে রোগ শনাক্ত করা হবে",
      "local_link": "লোকাল লিঙ্ক",
      "varanasi_node": "বারাণসী নোড V-01",
      "global_status": "বৈশ্বিক অবস্থা",
      "online_sync": "অনলাইন এবং সিঙ্ক হচ্ছে",
      "download_report": "কেয়ার রিপোর্ট V-01 (PDF) ডাউনলোড করুন",
      "fever": "তীব্র জ্বর",
      "cough": "টানা কাশি",
      "chest_pain": "বুকে তীব্র ব্যথা",
      "breathing": "শ্বাসকষ্ট",
      "bleeding": "তীব্র রক্তপাত",
      "headache": "তীব্র মাথাব্যথা",
      "vomiting": "বমি",
      "weakness": "অত্যন্ত দুর্বলতা",
      "dizziness": "মাথা ঘোরা",
      "vision_loss": "হঠাৎ দৃষ্টিশক্তি হ্রাস",
      "paralysis": "শরীরের একপাশে হঠাৎ দুর্বলতা"
    },
    "villagerDashboard": {
      "offline_active": "অফলাইন প্রোটোকল সক্রিয়",
      "decentralized_health": "বিকেন্দ্রীভূত স্বাস্থ্যসেবা। নিরাপদ পরিচয়। নিরবচ্ছিন্ন যত্ন।",
      "use_without_internet": "ইন্টারনেট ছাড়াই ব্যবহার করুন",
      "go_online": "অনলাইনে যান",
      "skin_scanner": "স্কিন এআই স্ক্যানার",
      "skin_scanner_desc": "ত্বকের সংক্রমণের জন্য ছবি আপলোড করুন।",
      "health_identity": "স্বাস্থ্য পরিচয়",
      "health_identity_desc": "আপনার ক্লিনিকাল ইতিহাস এবং স্বাস্থ্য আইডি পরিচালনা করুন।",
      "voice_assistant": "ভয়েস অ্যাসিস্ট্যান্ট",
      "voice_assistant_desc": "আপনার ভাষায় কথা বলুন। টাইপ করার প্রয়োজন নেই!"
    },
    "footer": {
      "empowering": "গ্রামীণ ভারতকে শক্তিশালী করা",
      "description": "গ্রামীণ ভারতের স্বাস্থ্যসেবার ব্যবধান দূর করা। SwasthAI Guardian এআই এবং স্থানীয় নেটওয়ার্ক ব্যবহার করে প্রতিটি গ্রামে তাৎক্ষণিক রোগ নির্ণয় এবং জরুরি সহায়তা প্রদান করে।",
      "quick_access": "দ্রুত অ্যাক্সেস",
      "connect": "যোগাযোগ",
      "regional_hub": "আঞ্চলিক হাব",
      "address": "বারাণসী, উত্তর প্রদেশ, ভারত",
      "support_line": "সহায়তা লাইন",
      "emergency_helplines": "জরুরি হেল্পলাইন",
      "national_health_axis": "জাতীয় স্বাস্থ্য এক্সিস",
      "asha_alert": "আশা কর্মী কুইক-অ্যালার্ট",
      "request_assist": "লোকাল সহায়তার অনুরোধ করুন",
      "secured_by": "SwasthAI প্রোটোকল দ্বারা সুরক্ষিত",
      "copyright": "© ২০২৬ SwasthAI Guardian। এআই উদ্ভাবনের মাধ্যমে গ্রামীণ স্বাস্থ্যসেবার আধুনিকীকরণের একটি মিশন।",
      "privacy": "গোপনীয়তা নীতি",
      "ethics": "ডিজিটাল নৈতিকতা"
    },
    "intro": {
      "welcome_title": "SwasthAI Guardian-এ স্বাগতম",
      "welcome_sub": "গ্রামীণ স্বাস্থ্যসেবার ভবিষ্যৎ এখানে। অফলাইন-তৈরি এবং এআই-চালিত।",
      "strategic_title": "কৌশলগত স্বাস্থ্য তদারকি",
      "service_1_t": "স্মার্ট এআই ডায়াগনস্টিকস",
      "service_1_d": "অফলাইন-সক্ষম এআই নোড ব্যবহার করে তাৎক্ষণিক স্বাস্থ্য মূল্যায়ন পান।",
      "service_2_t": "জরুরি প্রোটোকল",
      "service_2_d": "জরুরি অ্যাম্বুলেন্স এবং আশা কর্মী সতর্কবার্তা পাঠানোর জন্য এক্সেস।",
      "service_3_t": "মাতৃ ও মাসিক হাব",
      "service_3_d": "নারীদের সুস্বাস্থ্যের জন্য নিরাপদ, ব্যক্তিগত ট্র্যাকিং এবং ক্লিনিকাল গাইডেন্স।",
      "service_4_t": "টেলি-হেলথ ব্রিজ",
      "service_4_d": "শহুরে বিশেষজ্ঞদের সাথে সরাসরি উচ্চ-সংকোচন ভিডিও/অডিও পরামর্শ।",
      "service_5_t": "বিকেন্দ্রীভূত স্বাস্থ্য আইডি",
      "service_5_d": "এক নিরাপদ স্থানে আপনার পুরো পরিবারের জন্য ডিজিটাল মেডিকেল রেকর্ড পরিচালনা করুন।",
      "service_6_t": "স্কিন এআই স্ক্যানার",
      "service_6_d": "ত্বকের সংক্রমণ এবং কন্ডিশনের জন্য তাৎক্ষণিক ক্লিনিকাল-গ্রেড বিশ্লেষণ।",
      "protocol_awareness": "পরবর্তী: প্রোটোকল সচেতনতা",
      "select_title": "আপনার ভাষা নির্বাচন করুন",
      "select_sub": "একটি ভালো অভিজ্ঞতার জন্য আপনার পছন্দের ভাষা নির্বাচন করুন।",
      "establish_sync": "সিঙ্ক স্থাপন করুন"
    },
    "dashboardExt": {
      "maternal_pulse": "মাতৃ স্বাস্থ্য",
      "secure_axis": "নিরাপদ",
      "terminal_access": "খুলুন",
      "my_profile": "আমার প্রোফাইল",
      "profile_desc": "আপনার স্বাস্থ্য আইডি দেখুন, নাম अपडेट করুন।",
      "open": "খুলুন",
      "skin_ai": "স্কিন এআই স্ক্যানার",
      "skin_ai_desc": "সহজেই ত্বকের সংক্রমণ পরীক্ষা করুন।",
      "symptom_checker": "লক্ষণ পরীক্ষক",
      "symptom_checker_desc": "আপনার লক্ষণগুলি পরীক্ষা করুন এবং পরামর্শ পান।",
      "greeting": "নমস্কার, আজ আমরা আপনাকে কীভাবে সাহায্য করতে পারি?"
    },
    "menstrual": {
      "title": "নারীর স্বাস্থ্য",
      "safe_private": "নিরাপদ",
      "subtitle": "এআই স্বাস্থ্য নির্দেশিকা, লক্ষণ পরীক্ষা এবং বিনামূল্যে প্যাড - সম্পূর্ণ ব্যক্তিগত।",
      "emergency_help": "জরুরী সাহায্য",
      "ai_assistant": "এআই সহকারী",
      "symptom_check": "লক্ষণ পরীক্ষা",
      "request_pads": "প্যাডের জন্য অনুরোধ",
      "health_tips": "স্বাস্থ্য টিপস",
      "request_pads_title": "স্যানিটারি প্যাডের জন্য অনুরোধ করুন",
      "request_pads_desc": "আপনার আশা দিদি আপনাকে প্যাড সরবরাহ করবেন। এই অনুরোধটি সম্পূর্ণ গোপনীয়।",
      "private_note": "100% ব্যক্তিগত — শুধুমাত্র আপনার আশা দিদি এই অনুরোধ দেখতে পারবেন।",
      "your_village": "আপনার গ্রাম / এলাকা",
      "village_placeholder": "উদাঃ রামপুর, সেক্টর 4",
      "request_btn": "আশা দিদির কাছে প্যাডের অনুরোধ করুন",
      "request_sent": "অনুরোধ পাঠানো হয়েছে!",
      "request_sent_desc": "আপনার আশা দিদিকে জানানো হয়েছে, তিনি শীঘ্রই আপনার সাথে যোগাযোগ করবেন।",
      "send_another": "আরেকটি অনুরোধ পাঠান",
      "symptom_title": "লক্ষণ পরীক্ষা",
      "symptom_desc": "আপনার যেকোনো লক্ষণ নির্বাচন করুন। এটি কোনো রোগ নির্ণয় নয় - সর্বদা একজন ডাক্তারের পরামর্শ নিন।",
      "check_btn": "আমার লক্ষণ পরীক্ষা করুন",
      "tips_title": "স্বাস্থ্য টিপস",
      "tips_desc": "আপনার পিরিয়ড চলাকালীন আপনার স্বাস্থ্যের জন্য সহজ পরামর্শ।",
      "ask_anything": "আপনার স্বাস্থ্য সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন...",
      "emergency_title": "জরুরী সাহায্য",
      "emergency_desc": "আপনার আশা দিদিকে অবিলম্বে সতর্ক করতে নীচের বোতামটি চাপুন। তিনি আপনাকে কল করবেন এবং সাহায্য করতে আসবেন।",
      "alert_asha": "আমার আশা দিদিকে এখন সতর্ক করুন",
      "call_ambulance": "108-বিনামূল্যে অ্যাম্বুলেন্স কল করুন"
    },
    "ambulance": {
      "title": "জরুরী উদ্ধার",
      "subtitle": "অ্যাম্বুলেন্স বা স্বাস্থ্যকর্মী প্রয়োজন? নিচে ক্লিক করুন। আপনার অবস্থান স্বয়ংক্রিয়ভাবে শেয়ার করা হবে।",
      "request_team": "জরুরী দলের জন্য অনুরোধ করুন",
      "non_critical": "সাধারণ চিকিৎসা পরিবহন",
      "rescue_dispatched": "উদ্ধারকারী দল পাঠানো হয়েছে",
      "call_driver": "ড্রাইভারকে কল করুন",
      "dispatching": "পাঠানো হচ্ছে..."
    },
    "symptom": {
      "title": "এআই লক্ষণ পরীক্ষক",
      "subtitle": "আপনার কেমন লাগছে তা আমাদের জানান। এরপর কী করতে হবে তা আমরা আপনাকে জানাব।",
      "select_symptoms": "আপনার লক্ষণ নির্বাচন করুন:",
      "check_now": "এখন পরীক্ষা করুন",
      "fever": "জ্বর",
      "cough": "কাশি",
      "chest_pain": "বুকে ব্যথা",
      "breathing": "শ্বাসকষ্ট",
      "bleeding": "রক্তপাত",
      "headache": "মাথাব্যথা",
      "vomiting": "বমি",
      "weakness": "দুর্বলতা",
      "analyzing": "বিশ্লেষণ করা হচ্ছে...",
      "go_hospital": "অবিলম্বে হাসপাতালে যান",
      "see_doctor": "আজই একজন ডাক্তারের সাথে দেখা করুন",
      "mild": "মৃদু — বাড়িতে বিশ্রাম নিন"
    }
  }
}
export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('swasth_lang') || 'en';
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('swasth_lang', newLang);
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
